### ISSUE TITLE
[BUG]: Using Deck offline can cause the library to crash

### ISSUE THREAD

**Issue by Tormak9970** [Tormak9970/TabMaster#10]
**Describe the bug**
Sometimes having to connection can cause the library to crash.

**More Info**
I suspect this is related to the stores. The error I got said "can't call GetSomething (i forgot) of undefined"

**Solution**
friends and tags will also be an issue. Tags we can simply cache in settings, and load if no wifi. friends we can as well, however we also need to cache the games they own. We will also need a fallback for the scenario where somehow the user has no cache

**This issue is for tracking the bug**

**Comment by Tormak9970** [comment]
unable to reproduce the issue, not sure if it was even caused by tabMaster, closing.

**Comment by jessebofill** [comment]
wait i'm confused, i think that error is what i was talking about here https://github.com/Tormak9970/TabMaster/issues/9#issuecomment-1608305257
but i thought that was from the backend call you added in order to work in offline

**Comment by jessebofill** [comment]
reopened while we investigate the errors cause by adding those backend calls to save these settings

**Comment by jessebofill** [comment]
> **Solution** friends and tags will also be an issue. Tags we can simply cache in settings, and load if no wifi. friends we can as well, however we also need to cache the games they own. We will also need a fallback for the scenario where somehow the user has no cache
> 
We shouldn’t have to store the games in settings. Are they not cached by steam? Default tabs should just be pulling from the collections. They should be populated either way

**Comment by Tormak9970** [comment]
games friends own are not cached

**Comment by jessebofill** [comment]
> storing the ids

Ah I thought you meant games user owns
