### ISSUE TITLE
[FEAT]: Regex101 link for easily testing regex against your entire library

### ISSUE THREAD

**Issue by PartyWumpus** [Tormak9970/TabMaster#111]
**Is your feature request related to a problem? Please describe.**
If you want to use the regex filter, it is difficult to test it against your whole library without just setting up the filter and taking a look, even though there are great regex testers, you just can't easily load your entire steam library into them.

**Describe the solution you'd like**
A button, somewhere in tabMaster's UI (although I can't really find anywhere for it to go right now :/), that takes you to regex101, with the user's entire library prefilled in the 'test string' section. This can be done with `NavigateToExternalWeb(https://regex101.com/?flavor=javascript&testString=<text>)` where `<text>` is a list of all the user's games as a newline (`%0A`) seperated string. It can easily be converted into a valid url with the built in `encodeURIComponent()`

To be clear, this isn't a request from you, I plan on implementing this myself, I just want to know if you'd like it as a feature so I don't waste time making something you aren't going to accept.

An example would look something like this: `https://regex101.com/?flavor=javascript&testString=Ultrakill%0ADestiny%202%0AStarfield%0ARedmatch%202%0ASteamVR%0APistol%20Whip%0ABaldur%27s%20Gate%203%0ATeam%20Fortress%202%0APhasmophobia%0ABloons%20TD%206%0ASpaceChem%0ABattleBit%20Remastered%0A`, which looks like this
![image](https://github.com/Tormak9970/TabMaster/assets/48649272/83cb0139-95c8-443c-a663-7a627fa7d139)

**Comment by Tormak9970** [comment]
> **Is your feature request related to a problem? Please describe.** If you want to use the regex filter, it is difficult to test it against your whole library without just setting up the filter and taking a look, even though there are great regex testers, you just can't easily load your entire steam library into them.
> 
> **Describe the solution you'd like** A button, somewhere in tabMaster's UI (although I can't really find anywhere for it to go right now :/), that takes you to regex101, with the user's entire library prefilled in the 'test string' section. This can be done with `NavigateToExternalWeb(https://regex101.com/?flavor=javascript&testString=<text>)` where `<text>` is a list of all the user's games as a newline (`%0A`) seperated string. It can easily be converted into a valid url with the built in `encodeURIComponent()`
> 
> To be clear, this isn't a request from you, I plan on implementing this myself, I just want to know if you'd like it as a feature so I don't waste time making something you aren't going to accept.
> 
> An example would look something like this: `https://regex101.com/?flavor=javascript&testString=Ultrakill%0ADestiny%202%0AStarfield%0ARedmatch%202%0ASteamVR%0APistol%20Whip%0ABaldur%27s%20Gate%203%0ATeam%20Fortress%202%0APhasmophobia%0ABloons%20TD%206%0ASpaceChem%0ABattleBit%20Remastered%0A`, which looks like this ![image](https://user-images.githubusercontent.com/48649272/266805134-83cb0139-95c8-443c-a663-7a627fa7d139.png)

hmm, not sure if this is a good idea. How well can it handle a query with 1000s of strings? Also not the biggest fan of navigating to a web url like that, because deck controls won't work. I think a better solution would be a regex testing modal similar to this, but within the UI

**Comment by Tormak9970** [comment]
@PartyWumpus closing this for now, but would still love to see what an implementation of this might look like
