### ISSUE TITLE
[FLTR]: Streamable

### ISSUE THREAD

**Issue by Rumik** [Tormak9970/TabMaster#114]
**Describe the filter you'd like**
When Remote Play is enabled in Settings, games from authorised devices on the same network appear in the Library. Opening the menu shows a "Stream" button at the top of the usual list. The request is for a filter that includes all titles with the Stream button.

Thanks

**Comment by Tormak9970** [comment]
Oh interesting, I really like that idea

**Comment by Rumik** [comment]
Thank you :)

**Comment by Tormak9970** [comment]
complete as of https://github.com/Tormak9970/TabMaster/commit/4d007872da610f6f701442c4bbf700d69029448b
