### ISSUE TITLE
[FEAT]: Disable for account

### ISSUE THREAD

**Issue by Rumik** [Tormak9970/TabMaster#115]
I have multiple accounts that I switch between, with different collections. If I log in with an account other than the one I set up TabMaster with, it errors and asks me to correct the issues. I'm hesitant to do this as I suspect it will impact my main account. So it would be great to have the option to disable TabMaster for specific accounts.

**Comment by jessebofill** [comment]
What version are you on? I don’t think this should be happening and may be a bug. We switched a while back to having tab master separate for each account, so they shouldn’t conflict with each other.

**Comment by Rumik** [comment]
I'm using 1.5.0, I installed it today via Decky.

**Comment by jessebofill** [comment]
> I'm using 1.5.0, I installed it today via Decky.

Ok thanks. Let me do some testing and I’ll get back to you.

**Comment by jessebofill** [comment]
Oh wait I forgot individual accounts isn’t implemented in 1.5.0. It’s in the v2.0.0 which is in testing store now. Sorry, we’ve been working on this release for a few weeks so I forgot that feature wasn’t released yet. But it should solve your issue. Feel free to test out it, we actually kinda need people to test it so it can get released.

**Comment by Rumik** [comment]
Oh great! I'll check it out, thank you :)

**Comment by Rumik** [comment]
Yep that appears to be working now, thanks!

**Comment by jessebofill** [comment]
> Yep that appears to be working now, thanks!

No problem. Glad it works.
