### ISSUE TITLE
[FLTR]: Played in Last x Days

### ISSUE THREAD

**Issue by Rumik** [Tormak9970/TabMaster#122]
An Expansion of the Last Played filter, adding options for the past day, 7 days, month, year. Rather than having to specify dates. This way, games you’ve played recently are automatically updated.

thanks

**Comment by Tormak9970** [comment]
I think that's a great idea, should be able to have an option like the review score filter. @jessebofill thoughts?

**Comment by jessebofill** [comment]
> I think that's a great idea, should be able to have an option like the review score filter. @jessebofill thoughts?

I originally considered them when I first implemented it, but I decided against it because we would need to be constantly polling time changes and rebuilding the collections

**Comment by Tormak9970** [comment]
> > I think that's a great idea, should be able to have an option like the review score filter. @jessebofill thoughts?
> 
> I originally considered them when I first implemented it, but I decided against it because we would need to be constantly polling time changes and rebuilding the collections

Hmm good point. We could just do a check when we initially build it. Doesn't have to be live

**Comment by jessebofill** [comment]
Checking once per day wouldn’t be bad, but we’d have to figure out how to schedule it

**Comment by jessebofill** [comment]
> > > I think that's a great idea, should be able to have an option like the review score filter. @jessebofill thoughts?
> > 
> > 
> > I originally considered them when I first implemented it, but I decided against it because we would need to be constantly polling time changes and rebuilding the collections
> 
> Hmm good point. We could just do a check when we initially build it. Doesn't have to be live

Then it won’t update unless something else triggers rebuilds which defeats the point of having that feature

**Comment by Tormak9970** [comment]
> Checking once per day wouldn’t be bad, but we’d have to figure out how to schedule it

We could just check when the plugin inits

**Comment by jessebofill** [comment]
> > Checking once per day wouldn’t be bad, but we’d have to figure out how to schedule it
> 
> We could just check when the plugin inits

Yeah and maybe when waking from sleep too

**Comment by Tormak9970** [comment]
> > > > I think that's a great idea, should be able to have an option like the review score filter. @jessebofill thoughts?
> > > 
> > > 
> > > I originally considered them when I first implemented it, but I decided against it because we would need to be constantly polling time changes and rebuilding the collections
> > 
> > Hmm good point. We could just do a check when we initially build it. Doesn't have to be live
> 
> Then it won’t update unless something else triggers rebuilds which defeats the point of having that feature

That's fine for this imo, cause odds are people will shut down their deck at least once a day

**Comment by Tormak9970** [comment]
closing as this is complete as of https://github.com/Tormak9970/TabMaster/commit/75d74eb97f37f6c218bb62f7db19ea9ec124435e
