### ISSUE TITLE
Not muting UI sounds 

### ISSUE THREAD

**Issue by repparw** [Tormak9970/TabMaster#130]
UI edit menu sounds reproduce without checking if UI sounds are enabled on the deck

**Comment by Tormak9970** [comment]
> UI edit menu sounds reproduce without checking if UI sounds are enabled on the deck 

What update channel are you on? This is an issue across SteamOS on beta and preview afaik

**Comment by repparw** [comment]
All Stable. Decky, SteamOs, etc

**Comment by jessebofill** [comment]
> > UI edit menu sounds reproduce without checking if UI sounds are enabled on the deck
> 
> What update channel are you on? This is an issue across SteamOS on beta and preview afaik

It’s the custom elements that I added sounds to. I’m not sure if the method I used never respected system settings or if it changed.
