### ISSUE TITLE
[FLTR]: Steam Cloud support

### ISSUE THREAD

**Issue by evanjs** [Tormak9970/TabMaster#131]
#### Filter on games that support Steam Cloud
This would be especially helpful in reconciling save games after manual file transfers, e.g. LCD -> OLED Steam Deck.

Games that _do not_ support Steam Cloud could be easily identified and addressed as needed.
___
In discussing the presence/support of Steam Cloud, one issue was mentioned on the SteamDB server:
It can be difficult to tell if a game _actually_ supports Steam Cloud.

Many games will advertise support on the store page, but others might support Steam Cloud while not advertising support, and so on.
As such, it might be easiest to simply rely on "explicit" (i.e. "Store-visible") Steam Cloud support.
___
This filter would essentially bring [this filter](https://steamdb.info/sales/?displayOnly=OwnedGames&min_reviews=0&min_rating=0&min_discount=0&category=-23) to the interface on the Deck.

Note that the above is for games that _do not_ support Steam Cloud, which is the primary focus of this filter, but the toggle invert/"is" toggle for boolean filters would allow users to check for support or lack thereof.

e.g. "Supports Steam Cloud? [Yes]/no"
___
Additionally, it might be worth investigating other "Store page visible" features if they take just as much effort to implement/query
Other features such as "Steam Achievements", "VR Only", "Single-player", etc.

Bringing it up now as it could help envision what the UI might look like in the long run, especially if more features are added.

**Comment by Tormak9970** [comment]
@evanjs We've implemented a filter for Steam could support, but I'm not sure if we will do other store categories. In theory they would be just as simple as the tags filter, but the vast majority of them are already covered by the tags filter, and there's no easy way to get their label

**Comment by Tormak9970** [comment]
complete as of https://github.com/Tormak9970/TabMaster/commit/2a3e6abbf8d1d339fde2a8f2b09c9a257d163248

**Comment by evanjs** [comment]
Wanted to leave a note regarding current behavior for anybody else that notices the filter seems a bit... off.

This is expected, and is due to how many games on Steam have features that may not match what is explicitly stated on the store page.

A game might support cloud saves but not list "Steam Cloud support" on the store page
This means the game will not be shown under "Supports Cloud Saves", even though it _does_ support Steam Cloud.

This is an unfortunate consequence of relying solely on the features advertised on the store page.

That being said, this is the best/most succinct approach for the time being.
