### ISSUE TITLE
[BUG]: wrong filter shown when deleting a filter

### ISSUE THREAD

**Issue by jessebofill** [Tormak9970/TabMaster#132]
When deleting a filter the it shows the deleted filter type on the next remaining filter instead of the correct filter type.

**To Reproduce**
1. have multiple filters of different types. ex: filter 1: collection, filter 2: regex
2. delete a filter that's not last. ex: delete first filter (collection)
3. the next remaining filter will show the deleted filter's type instead of it's own type. ex: remaining filter type now shows "collection" instead of "regex"

**Comment by Tormak9970** [comment]
fixed as of https://github.com/Tormak9970/TabMaster/commit/d78a0f51a614a9a691ce790df0f4a53e1ed66122
