### ISSUE TITLE
[BUG]: Whitelist filter forgets previous params when saving

### ISSUE THREAD

**Issue by jessebofill** [Tormak9970/TabMaster#133]
The whitelist filter forget it's previously saved parameters in edit modal whenever saving the tab. Only changes that were made in current editing session will be saved.

1. create a tab with a whitelist filter and add some whitelisted games then save the tab.
2. edit the tab. previously whitelisted games will still be there. save the tab again without making changes.
3. edit tab again, and whitelist games are no longer there.

*note: this happens with whitelist filter and i assume blacklist filter but haven't tested. I have tested friends and tags filters, and this does not happen. other filters that use multi select have not been tested.

**Comment by Tormak9970** [comment]
additional notes:
- already added games show up in search modal
- when the games are removed, they also disappear from the rendered tab, so they are actually getting removed, not just a rendering issue

**Comment by Tormak9970** [comment]
the issue also occurs if you open/close the whitelist accordion twice, even without saving. the gameids in the params are getting set to undefined somehow

**Comment by Tormak9970** [comment]
the loss of selected entries is fixed but also need to fix the fact that you can select multiple of the same game
