### ISSUE TITLE
[FEAT]: Blacklist for Collections

### ISSUE THREAD

**Issue by amcgready** [Tormak9970/TabMaster#135]
**Is your feature request related to a problem? Please describe.**
Currently I stream games from my PC to my Steam Deck. I have a tab setup to show installed and streamable games. Unfortunately I also have all my ROMs in Steam so this tab shows thousands of results. 
**Describe the solution you'd like**
I would like to be able to blacklist certain collections from appearing in a tab. For example, with my tab I spoke of before, it would be nice to have that tab exclude anything in the 'Emulation' collection.

**Comment by jessebofill** [comment]
> Well...I feel dumb. Thanks for the quick reaponse.
> […](#)

No problem, happy to help
