### ISSUE TITLE
[BUG]: TabMaster stopped mastering tabs

### ISSUE THREAD

**Issue by Intoxicus** [Tormak9970/TabMaster#138]
**Describe the bug**
TabMaster no longer Masters Tabs after most recent Steam Client Update

**To Reproduce**
1. Update to Dec 13 Steam Client Beta

**Expected behavior**
Tab Master no longer works and shows  "loading..." instead of any settings in the decky settings menu.

**Screenshots**

**Logs**:
[2023-12-12 20:49:01,078][INFO]: Initializing Tab Master.
[2023-12-12 20:49:52,080][INFO]: [front-end]: User logged in. [DEBUG] username: ikarius_intoxicus.
[2023-12-12 20:49:52,081][INFO]: [front-end]: Services found.
[2023-12-12 20:49:52,086][INFO]: [front-end]: Services initialized. Success: true
[2023-12-12 20:49:52,090][INFO]: [front-end]: PluginController initialized.
[2023-12-12 20:49:52,094][INFO]: active user id: 24538930
[2023-12-12 20:49:52,100][INFO]: [front-end]: No Legacy Settings found.

**Enviroment Info:**
 - SteamOS Version: 3.5.10 /Beta Steam Client
 - SteamOS Update Channel: Preview
 - Decky Version: 2.10.10 pre 1
 - Decky Update: Channel PreRelease
 - TabMaster Version: 2.1.0

**Comment by Tormak9970** [comment]
> **Describe the bug**
> TabMaster no longer Masters Tabs after most recent Steam Client Update
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Update to Dec 13 Steam Client Beta
> 
> **Expected behavior**
> Tab Master no longer works and shows  "loading..." instead of any settings in the decky settings menu.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Logs**:
> Pending
> 
> **Enviroment Info:**
>  - SteamOS Version: 3.5.10 /Beta Steam Client
>  - SteamOS Update Channel: Preview
>  - Decky Version: 2.10.10 pre 1
>  - Decky Update: Channel PreRelease
>  - TabMaster Version: 2.1.0
> 

I believe this is a known issue with decky, not TabMaster specifically

**Comment by Intoxicus** [comment]
They updated decky. only tabmaster is broken atm

**Comment by Intoxicus** [comment]
[2023-12-12 20:49:01,078][INFO]: Initializing Tab Master.
[2023-12-12 20:49:52,080][INFO]: [front-end]: User logged in. [DEBUG] username: ikarius_intoxicus.
[2023-12-12 20:49:52,081][INFO]: [front-end]: Services found.
[2023-12-12 20:49:52,086][INFO]: [front-end]: Services initialized. Success: true
[2023-12-12 20:49:52,090][INFO]: [front-end]: PluginController initialized.
[2023-12-12 20:49:52,094][INFO]: active user id: 24538930
[2023-12-12 20:49:52,100][INFO]: [front-end]: No Legacy Settings found.

**Comment by Tormak9970** [comment]
fixed as of https://github.com/Tormak9970/TabMaster/commit/b9d8a1d05e6b380a29f2acca48f0bfa4941d63fd. Unfortunately, we can't release these fixes until those changes come to the stable channel, because they changed the MobX version, and once we do that, it won't work with older versions (so current stable will break)

**Comment by Intoxicus** [comment]
Thank you

**Comment by Intoxicus** [comment]
> fixed as of https://github.com/Tormak9970/TabMaster/commit/b9d8a1d05e6b380a29f2acca48f0bfa4941d63fd. Unfortunately, we can't release these fixes until those changes come to the stable channel, because they changed the MobX version, and once we do that, it won't work with older versions (so current stable will break)

Decky updated Stable finally :)

**Comment by Tormak9970** [comment]
> > fixed as of https://github.com/Tormak9970/TabMaster/commit/b9d8a1d05e6b380a29f2acca48f0bfa4941d63fd. Unfortunately, we can't release these fixes until those changes come to the stable channel, because they changed the MobX version, and once we do that, it won't work with older versions (so current stable will break)
> 
> Decky updated Stable finally :)

I mean that Steam has to ship the changes to its stable branch, not decky

**Comment by Intoxicus** [comment]
Oh...

**Comment by Tormak9970** [comment]
> Oh...

I'm going to make a pre-release that should fix it once our next update goes live. Should be within the next few days

**Comment by Intoxicus** [comment]
> > Oh...
> 
> I'm going to make a pre-release that should fix it once our next update goes live. Should be within the next few days

Thank you!

Your plugin kicks ass!

**Comment by Tormak9970** [comment]
Glad to hear you're enjoying it, we've put a lot of hard work into making it the best we can. Here's the release with the fixes you need: [release v2.3.1](https://github.com/Tormak9970/TabMaster/releases/tag/v2.3.1)

**Comment by Intoxicus** [comment]
Thank you!

**Comment by Fofer** [comment]
> I mean that Steam has to ship the changes to its stable branch

They have, I'm on the stable branch and it just updated today, which broke TabMaster.  Another report here:
https://github.com/Tormak9970/TabMaster/issues/148

**Comment by Tormak9970** [comment]
> > I mean that Steam has to ship the changes to its stable branch
> 
> They have, I'm on the stable branch and it just updated today, which broke TabMaster.  Another report here:
> https://github.com/Tormak9970/TabMaster/issues/148

We're aware, this issue was closed well before that happened. We're working on pushing that update to live
