### ISSUE TITLE
Tab Master just shows "Loading..." in the QAM sidebar

### ISSUE THREAD

**Issue by mcswizzle** [Tormak9970/TabMaster#144]
**Describe the bug**
Tab Master just shows "Loading..." in the QAM sidebar

**To Reproduce**
Unknown how this issue started. Once the issue shows itself, press the QAM button, go to Tab Master, and view that it only shows "Loading..." in the side bar and current tabs never load.

**Expected behavior**
Tabs are shown and able to be added to, hidden, and edited.

**Logs**:
Fresh logs were taken immediately after removing Tab Master's directory in the "Data" ~/home/Deck/homebrew sub-directory, and after performing a Reinstall from within Decky:

```
[2023-12-19 03:57:18,818][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,818][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,842][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,861][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,863][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,882][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,888][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,890][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,894][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,894][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,908][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,911][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,912][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,917][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,923][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,927][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,933][INFO]: Initializing Tab Master.
[2023-12-19 03:57:18,936][INFO]: Initializing Tab Master.
[2023-12-19 03:57:19,137][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:19,243][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:19,310][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:19,372][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:19,428][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:19,482][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:19,533][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:19,583][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:19,662][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:19,725][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,812][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,814][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,816][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,818][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,818][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,826][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,826][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,828][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,830][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,830][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,838][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,844][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,846][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,846][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,849][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,850][INFO]: Calling Loader unload function.
[2023-12-19 03:57:20,851][INFO]: Calling Loader unload function.
```
and 
```
[2023-12-19 03:57:19,765][INFO]: Initializing Tab Master.
[2023-12-19 03:57:21,737][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:21,740][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:21,744][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:21,760][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:21,796][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:21,885][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:21,958][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:22,032][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:22,102][INFO]: [front-end]: PluginController dismounted.
[2023-12-19 03:57:22,183][INFO]: [front-end]: User logged in. [DEBUG] username: [my Steam login email].
[2023-12-19 03:57:22,185][INFO]: [front-end]: Services found.
[2023-12-19 03:57:22,187][INFO]: [front-end]: Services initialized. Success: true
[2023-12-19 03:57:22,190][INFO]: [front-end]: PluginController initialized.
[2023-12-19 03:57:22,192][INFO]: active user id: [My User ID, removed in case of uniqueness/privacy concerns]
[2023-12-19 03:57:22,193][INFO]: User 3513638 had no settings.
[2023-12-19 03:57:22,199][INFO]: [front-end]: No Legacy Settings found.
```

**Enviroment Info:**
 - SteamOS Version: 3.5.7
 - SteamOS Update Channel: Beta
 - Decky Version: 2.10.11-pre1
 - Decky Update Channel: Pre-release (due to Decky issues in stable build)
 - TabMaster Version: 2.1.0

**Comment by mcswizzle** [comment]
Downgrading to Tab Master 2.0 did not solve this issue. I am hesitant to go any lower given compatibility with SteamOS 3.5.

**Comment by mcswizzle** [comment]
Moving SteamOS from Beta to Stable resolved this. I had issues at the time with applying Community control profiles in Stable. Unrelated, this also seems to be resolved.

**Comment by Thesola10** [comment]
Please reopen, issue still occurs for me.

**Comment by minitaba** [comment]
Newest Steam OS stable version, this same issue happens again

**Comment by mcswizzle** [comment]
Note: You'll have to edit the permissions on /home/deck/homebrew/plugins/TabMaster to allow write access to the folder. 
Since the main TabMaster page just says to update via Decky's plugin store, here's how to do it via GUI:

1. Open Dolphin file browser
2. Open "homebrew"
3. Find and Left Trigger on "plugins" and select Properties.
4. Select the Permissions tab and set Owner to "Can View & Modify Content", then select OK at the bottom.
5. Open "plugins"
6. Delete the "TabMaster" folder
7. Go back up one directory to "homebrew" with the < (back) button of Dolphin
8. Open the .zip file you got from https://github.com/Tormak9970/TabMaster/releases/tag/v2.4.0 and extract so the TabMaster folder goes into the "plugins" folder. You can drag and drop it onto the "plugins" folder if you want to. Make sure the "TabMaster" folder lands inside the "plugins" folder, and not in the "homebrew" folder.
9. Left Trigger "plugins" again, click "Permissions" and set the permissions back to "Can Only View Content".
10. Boot back into Game Mode and see that TabMaster works again, without losing your settings.

And via terminal: 
$ chmod -R ugo+w /home/deck/homebrew/plugins/TabMaster
$ cd ~/Downloads/
$ unzip TabMaster_v2.4.0.zip# I think SteamOS comes with unzip. I don't remember if I added it myself or not.
$ rm -rf /home/deck/homebrew/plugins/TabMaster/*
$ mv TabMaster/* ~/homebrew/plugins/TabMaster
$ rmdir TabMaster
$ chmod -R ugo-w /home/deck/homebrew/plugins/TabMaster

**Comment by Tormak9970** [comment]
> Since the main TabMaster page just says to update via Decky's plugin store, here's how to do it via GUI:
> 
> The Game Mode native option is to Enable "Developer mode" in Decky's general options, then go to Developer in the left side of options and choose Install Plugin from ZIP File, then point it to the zip you downloaded from the 2.4.0 release page. This is probably easiest. Though if you want to do it manually, here's how:
> 
> Note: You'll have to edit the permissions on /home/deck/homebrew/plugins/TabMaster to allow write access to the folder.
> 
>     1. Open Dolphin file browser
> 
>     2. Open "homebrew"
> 
>     3. Find and Left Trigger on "plugins" and select Properties.
> 
>     4. Select the Permissions tab and set Owner to "Can View & Modify Content", then select OK at the bottom.
> 
>     5. Open "plugins"
> 
>     6. Delete the "TabMaster" folder
> 
>     7. Go back up one directory to "homebrew" with the < (back) button of Dolphin
> 
>     8. Open the .zip file you got from https://github.com/Tormak9970/TabMaster/releases/tag/v2.4.0 and extract so the TabMaster folder goes into the "plugins" folder. You can drag and drop it onto the "plugins" folder if you want to. Make sure the "TabMaster" folder lands inside the "plugins" folder, and not in the "homebrew" folder.
> 
>     9. Left Trigger "plugins" again, click "Permissions" and set the permissions back to "Can Only View Content".
> 
>     10. Boot back into Game Mode and see that TabMaster works again, without losing your settings.
> 
> 
> And via terminal: $ chmod -R ugo+w /home/deck/homebrew/plugins/TabMaster $ cd ~/Downloads/ $ unzip TabMaster_v2.4.0.zip #I think SteamOS comes with unzip. I don't remember if I added it myself or not. $ rm -rf /home/deck/homebrew/plugins/TabMaster/* $ mv TabMaster/* ~/homebrew/plugins/TabMaster $ rmdir TabMaster $ chmod -R ugo-w /home/deck/homebrew/plugins/TabMaster

You should be able to install via Decky's install from zip feature (you may need to restart after installing it if it does not show up immediately). To do so:

1. Download v2.4.0 from releases [here](https://github.com/Tormak9970/TabMaster/releases/tag/v2.4.0) (save it to your deck's Desktop or somewhere else that's easy to access)
2. Go into Game Mode
3. In Decky's settings, navigate to the "Developer" tab
4. Click "Install from Zip", and select the zip you downloaded

**Comment by Tormak9970** [comment]
I'm going to reopen this until Decky fixes their release system

**Comment by ThisByzantineConduit** [comment]
I was able to successfully install 2.4 manually, but now all of the default Steam Tabs I had hidden (which are supposed to be locked with the Steam Logo) disappeared. I was able to recreate my custom tabs but all the default ones disappeared in TabMaster. Not a big deal but any idea why? Thanks!

**Comment by ThisByzantineConduit** [comment]
> > Since the main TabMaster page just says to update via Decky's plugin store, here's how to do it via GUI:
> 
> > 
> 
> > The Game Mode native option is to Enable "Developer mode" in Decky's general options, then go to Developer in the left side of options and choose Install Plugin from ZIP File, then point it to the zip you downloaded from the 2.4.0 release page. This is probably easiest. Though if you want to do it manually, here's how:
> 
> > 
> 
> > Note: You'll have to edit the permissions on /home/deck/homebrew/plugins/TabMaster to allow write access to the folder.
> 
> > 
> 
> >     1. Open Dolphin file browser
> 
> > 
> 
> >     2. Open "homebrew"
> 
> > 
> 
> >     3. Find and Left Trigger on "plugins" and select Properties.
> 
> > 
> 
> >     4. Select the Permissions tab and set Owner to "Can View & Modify Content", then select OK at the bottom.
> 
> > 
> 
> >     5. Open "plugins"
> 
> > 
> 
> >     6. Delete the "TabMaster" folder
> 
> > 
> 
> >     7. Go back up one directory to "homebrew" with the < (back) button of Dolphin
> 
> > 
> 
> >     8. Open the .zip file you got from https://github.com/Tormak9970/TabMaster/releases/tag/v2.4.0 and extract so the TabMaster folder goes into the "plugins" folder. You can drag and drop it onto the "plugins" folder if you want to. Make sure the "TabMaster" folder lands inside the "plugins" folder, and not in the "homebrew" folder.
> 
> > 
> 
> >     9. Left Trigger "plugins" again, click "Permissions" and set the permissions back to "Can Only View Content".
> 
> > 
> 
> >     10. Boot back into Game Mode and see that TabMaster works again, without losing your settings.
> 
> > 
> 
> > 
> 
> > And via terminal: $ chmod -R ugo+w /home/deck/homebrew/plugins/TabMaster $ cd ~/Downloads/ $ unzip TabMaster_v2.4.0.zip #I think SteamOS comes with unzip. I don't remember if I added it myself or not. $ rm -rf /home/deck/homebrew/plugins/TabMaster/* $ mv TabMaster/* ~/homebrew/plugins/TabMaster $ rmdir TabMaster $ chmod -R ugo-w /home/deck/homebrew/plugins/TabMaster
> 
> 
> 
> You should be able to install via Decky's install from zip feature (you may need to restart after installing it if it does not show up immediately). To do so:
> 
> 
> 
> 1. Download v2.4.0 from releases [here](https://github.com/Tormak9970/TabMaster/releases/tag/v2.4.0) (save it to your deck's Desktop or somewhere else that's easy to access)
> 
> 2. Go into Game Mode
> 
> 3. In Decky's settings, navigate to the "Developer" tab
> 
> 4. Click "Install from Zip", and select the zip you downloaded

I was able to successfully install 2.4 manually, but now all of the default Steam Tabs I had hidden (which are supposed to be locked with the Steam Logo) disappeared. I was able to recreate my custom tabs but all the default ones disappeared in TabMaster. Not a big deal but any idea why? Thanks!

**Comment by Tormak9970** [comment]
> I was able to successfully install 2.4 manually, but now all of the default Steam Tabs I had hidden (which are supposed to be locked with the Steam Logo) disappeared. I was able to recreate my custom tabs but all the default ones disappeared in TabMaster. Not a big deal but any idea why? Thanks!

Sounds like Decky overwrote your settings or something. That's quite odd, not sure why

**Comment by ThisByzantineConduit** [comment]
Hmm, I have a feeling it has something to do with manually changing the permissions and deleting the TabMaster folder in /homebrew/plugins before extracting the 2.4 zip there. I did this because even with permissions on for root and all subfolders, it wouldn't overwrite the existing version.

I later remembered that you can install plugins from a link or ZIP file in Gaming Mode with Dev Mode enabled, but it was too late at that point.



> > I was able to successfully install 2.4 manually, but now all of the default Steam Tabs I had hidden (which are supposed to be locked with the Steam Logo) disappeared. I was able to recreate my custom tabs but all the default ones disappeared in TabMaster. Not a big deal but any idea why? Thanks!
> 
> Sounds like Decky overwrote your settings or something. That's quite odd, not sure why

**Comment by Tormak9970** [comment]
> Hmm, I have a feeling it has something to do with manually changing the permissions and deleting the TabMaster folder in /homebrew/plugins before extracting the v2.4 zip there. I did this because even with permissions on for root and all subfolders, it wouldn't overwrite the existing version.
> 
> I later remembered that you can install plugins from a link or ZIP file in Gaming Mode with Dev Mode enabled, but it was too late at that point.
> 
> 
> 
> > > I was able to successfully install 2.4 manually, but now all of the default Steam Tabs I had hidden (which are supposed to be locked with the Steam Logo) disappeared. I was able to recreate my custom tabs but all the default ones disappeared in TabMaster. Not a big deal but any idea why? Thanks!
> > 
> > Sounds like Decky overwrote your settings or something. That's quite odd, not sure why
> 
> 

Ahh, yea you prob deleted the settings

**Comment by ThisByzantineConduit** [comment]
> > Hmm, I have a feeling it has something to do with manually changing the permissions and deleting the TabMaster folder in /homebrew/plugins before extracting the v2.4 zip there. I did this because even with permissions on for root and all subfolders, it wouldn't overwrite the existing version.
> > 
> > I later remembered that you can install plugins from a link or ZIP file in Gaming Mode with Dev Mode enabled, but it was too late at that point.
> > 
> > 
> > 
> > > > I was able to successfully install 2.4 manually, but now all of the default Steam Tabs I had hidden (which are supposed to be locked with the Steam Logo) disappeared. I was able to recreate my custom tabs but all the default ones disappeared in TabMaster. Not a big deal but any idea why? Thanks!
> > > 
> > > Sounds like Decky overwrote your settings or something. That's quite odd, not sure why
> > 
> > 
> 
> Ahh, yea you prob deleted the settings

Thanks for the quick replies!

Is there per chance way to restore them? I'm about to swap to a new Deck when my OLED comes in a few days so it'll be a non-issue, but I'm curious for my future reference if there is an easy way to restore those kind of files.

**Comment by Tormak9970** [comment]
> > > Hmm, I have a feeling it has something to do with manually changing the permissions and deleting the TabMaster folder in /homebrew/plugins before extracting the v2.4 zip there. I did this because even with permissions on for root and all subfolders, it wouldn't overwrite the existing version.
> > > 
> > > I later remembered that you can install plugins from a link or ZIP file in Gaming Mode with Dev Mode enabled, but it was too late at that point.
> > > 
> > > 
> > > 
> > > > > I was able to successfully install 2.4 manually, but now all of the default Steam Tabs I had hidden (which are supposed to be locked with the Steam Logo) disappeared. I was able to recreate my custom tabs but all the default ones disappeared in TabMaster. Not a big deal but any idea why? Thanks!
> > > > 
> > > > Sounds like Decky overwrote your settings or something. That's quite odd, not sure why
> > > 
> > > 
> > 
> > Ahh, yea you prob deleted the settings
> 
> Thanks for the quick replies!
> 
> Is there per chance way to restore them? I'm about to swap to a new Deck when my OLED comes in a few days so it'll be a non-issue, but I'm curious for my future reference if there is an easy way to restore those kind of files.

Sadly no, if they're overwritten like it sounds. Normally, they're preserved across updates

**Comment by ThisByzantineConduit** [comment]
> > > > Hmm, I have a feeling it has something to do with manually changing the permissions and deleting the TabMaster folder in /homebrew/plugins before extracting the v2.4 zip there. I did this because even with permissions on for root and all subfolders, it wouldn't overwrite the existing version.
> > > > 
> > > > I later remembered that you can install plugins from a link or ZIP file in Gaming Mode with Dev Mode enabled, but it was too late at that point.
> > > > 
> > > > 
> > > > 
> > > > > > I was able to successfully install 2.4 manually, but now all of the default Steam Tabs I had hidden (which are supposed to be locked with the Steam Logo) disappeared. I was able to recreate my custom tabs but all the default ones disappeared in TabMaster. Not a big deal but any idea why? Thanks!
> > > > > 
> > > > > Sounds like Decky overwrote your settings or something. That's quite odd, not sure why
> > > > 
> > > > 
> > > 
> > > Ahh, yea you prob deleted the settings
> > 
> > Thanks for the quick replies!
> > 
> > Is there per chance way to restore them? I'm about to swap to a new Deck when my OLED comes in a few days so it'll be a non-issue, but I'm curious for my future reference if there is an easy way to restore those kind of files.
> 
> Sadly no, if they're overwritten like it sounds. Normally, they're preserved across updates

OK, thanks. Appreciate the responsiveness to questions. Thanks for your work for the community!

**Comment by Tormak9970** [comment]
Closing this as v2.4.0 is now live

**Comment by zkhribach** [comment]
i have the same issue now :/
