### ISSUE TITLE
[FEAT]: Save and load tab groups

### ISSUE THREAD

**Issue by ArnoldSmith86** [Tormak9970/TabMaster#145]
**Is your feature request related to a problem? Please describe.**
I would like to show different tabs based on the local player count. So if there are 4 players on the couch, every single game has support for four local players and I can create tabs for genres, ratings or play modes (coop and vs).

**Describe the solution you'd like**
You can already hide and show tabs. I would just need some kind of shortcut to hide and show multiple tabs.

The easiest solution would probably be to save the currently visible tabs as a "tab group" (or whatever) and make them loadable again.

**Comment by jessebofill** [comment]
Interesting idea. I think we can do that.

**Comment by ArnoldSmith86** [comment]
If there was an API of some sort, I could even automate it using udev rules. But that would just be the icing on the cake.

**Comment by Tormak9970** [comment]
> If there was an API of some sort, I could even automate it using udev rules. But that would just be the icing on the cake.

If we implement this it will be done automatically, no need to automate it

**Comment by jessebofill** [comment]
> > If there was an API of some sort, I could even automate it using udev rules. But that would just be the icing on the cake.
> 
> If we implement this it will be done automatically, no need to automate it

I think he means automate how/ when different sets get applied

**Comment by ArnoldSmith86** [comment]
Yeah, I meant applying the "4 player" set whenever 4 controllers are connected. But switching by pressing a few buttons would already be awesome.

**Comment by Tormak9970** [comment]
> Yeah, I meant applying the "4 player" set whenever 4 controllers are connected. But switching by pressing a few buttons would already be awesome.

Yea we would automate that for you if we add this. So a tab set to "3 players" would show if 3 controllers are connected

**Comment by jessebofill** [comment]
> > Yeah, I meant applying the "4 player" set whenever 4 controllers are connected. But switching by pressing a few buttons would already be awesome.
> 
> Yea we would automate that for you if we add this. So a tab set to "3 players" would show if 3 controllers are connected

Tormak I think doing this is out of scope and the groups should just be generic (ie not based on # of players specifically) and the user can just apply whatever group they want at any time

**Comment by jessebofill** [comment]
Maybe we could add some hooks that the user can choose which would auto apply a group, but I think they should be generic and extendable

**Comment by Tormak9970** [comment]
> Maybe we could add some hooks that the user can choose which would auto apply a group, but I think they should be generic and extendable 

Yea or like a tab visibility menu or something

**Comment by jessebofill** [comment]
> > Maybe we could add some hooks that the user can choose which would auto apply a group, but I think they should be generic and extendable
> 
> Yea or like a tab visibility menu or something

Yeah I already have a basic idea for base creating/ applying that we can add upon. I’ll show you what I’m thinking here soon

**Comment by Tormak9970** [comment]
complete as of https://github.com/Tormak9970/TabMaster/commit/2ac43daeb9f12a5e93a291c09e8267243ec0b8da. Should be included in the next release after v2.3.0 (which is in testing)

**Comment by ArnoldSmith86** [comment]
Thanks! Looked at the diff and it sounds amazing. Looking forward to seeing it in production. 🤩

**Comment by jessebofill** [comment]
> production

Right now we’ve only added profiles that can be applied manually. We decided to implement a different system that would allow to auto hide individual tabs based on certain conditions for cases where automating tab visibility is desired. This would work independently of profiles though. So stay tuned for that in the future.
