### ISSUE TITLE
[BUG]: TabMaster not working after updating to latest Steam Client (Jan. 11 2024)

### ISSUE THREAD

**Issue by midnightcatwalk** [Tormak9970/TabMaster#148]
**Describe the bug**
Tabmaster categories do not appear in the Library section at all, being replaced by the default ones (“Great on Deck”, etc.) The Tabmaster plugin itself does not load, even after refreshing/reinstalling.

**To Reproduce**
1. Update to Jan. 11th Steam Client (latest Stable OS)
2. Restart

**Expected behavior**
For my lovingly reorganized Library tabs to appear

**Comment by Fofer** [comment]
Looks like the fix is in 2.3.1 which will probably go live soon now that this Steam Client release is out of beta:

https://github.com/Tormak9970/TabMaster/issues/138#issuecomment-1858876159

**Comment by Tormak9970** [comment]
If you want an immediate fix, you can download this release https://github.com/Tormak9970/TabMaster/releases/tag/v2.4.0

**Comment by Tormak9970** [comment]
The fix will be included in the next update for TabMaster, v2.4.0

**Comment by Tormak9970** [comment]
There are still issues with the Decky release system, we will track progress in #144
