### ISSUE TITLE
[BUG]: Tabmaster stays on "Loading..."

### ISSUE THREAD

**Issue by Panja0** [Tormak9970/TabMaster#149]
**Describe the bug**
Tab Master shows "Loading..." in QAM.
Tabs and hidden tabs are _**not**_ shown.

**To Reproduce**
Everything was working perfectly until this morning (I think).
I have removed an non-steam entry out of my Steam Library (Manage --> Remove non-Steam game from Library)
This entry was part of a custom tab created by Tabmaster. It seems the problem I'm facing happend after this.

**Expected behavior**
Tabs are shown, I can edit, add and remove tabs.

**Logs**:
[2024-01-12 09.55.53.log](https://pastebin.com/LSzLY02z)
[2024-01-12 09.58.02.log](https://pastebin.com/e1WdcvuU)
[2024-01-12 10.01.10.log](https://pastebin.com/1wXfbc9K)
[2024-01-12 10.01.11.log](https://pastebin.com/V71nfxgR)

**Enviroment Info:**
 - SteamOS Version: 3.5.7
 - SteamOS Update Channel: Stable
 - Decky Version: 2.10.10
 - Decky Update Channel: Stable
 - TabMaster Version: 2.1.0
 - Hardware: Steam Deck OLED 512GB

**Troubleshooting:**
- Numerous times removing and reinstalling Tabmaster.
- Removing all the Tabmaster related files in `~/homebrew`
- Changing the Decky store to pre-release so I could install  Tabmaster 2.3.0

**Comment by eXhumer** [comment]
I have the same issue, except I just fresh installed TabMaster on my Steam Deck. I previously used it without issue, but had to reimage my Steam Deck yesterday as I upgraded my SSD. Ever since then, the tabs section is stuck at "Loading..." forever. I have tried to add a new tab to see if it changes anything, but nothing changes even if I add a new tab with the "Add Tab" button. I am currently using v2.1.0 on the stable update channel.

**Comment by Tormak9970** [comment]
> After the official steam update on 1/11/24, looks like it modified some dependencies for Tab master and it broke :(

They bumped a library we use. Our dev branch already has the fix, we just need to push it to the testing store

**Comment by Tormak9970** [comment]
If you want an immediate fix, you can download this release https://github.com/Tormak9970/TabMaster/releases/tag/v2.4.0

**Comment by Tormak9970** [comment]
The fix will be included in the next update for TabMaster, v2.4.0

**Comment by NDC89** [comment]
Thank you very much!

love the Tabmaster add-on its amazing!

**Comment by Tormak9970** [comment]
There are still issues with the Decky release system, we will track progress in #144

**Comment by Panja0** [comment]
Just installed v2.4.0 and it works wonders (again)!
Many thanks for the hard work. Loving it!
