### ISSUE TITLE
[FLTR]: Not in Collection

### ISSUE THREAD

**Issue by Brendan-Stubbs** [Tormak9970/TabMaster#152]
Pretty much as the title suggests. A use case would be: I have a collection called "complete", I can then show all of my incomplete games in a tab by filtering by not in collection "complete"

**Comment by Tormak9970** [comment]
> Pretty much as the title suggests. A use case would be: I have a collection called "complete", I can then show all of my incomplete games in a tab by filtering by not in collection "complete"

If you make a tab with the collection set to "complete" and change the "default" option to "inverted", it should include all games not inthe "complete collection

**Comment by Brendan-Stubbs** [comment]
Thank you. Not sure how I missed that. The gift that keeps on giving 😀
