### ISSUE TITLE
[BUG]: Latest update breaks tabmaster

### ISSUE THREAD

**Issue by Cyan101** [Tormak9970/TabMaster#153]
**Describe the bug**
Basically the latest update breaks TabMaster and it just doesn't do anything.

Have restarted multiple times, reloaded, reinstalled.

**Comment by Tormak9970** [comment]
Release v2.4.0 contains the fixes for this (steam shipped beta to stable and broke things, we've known about this issue for a while). We're having some issues with the Decky store, but hopefully should be live soon

**Comment by Tormak9970** [comment]
There are still issues with the Decky release system, we will track progress in #144
