### ISSUE TITLE
[FEAT]: Auto Hide Tabs with Zero Games

### ISSUE THREAD

**Issue by ArchaicBubba** [Tormak9970/TabMaster#155]
I have a tab that is used specifically for in home game streaming. As such when I am away from the house on long trips this tab is marked as having 0 games. It would be awesome to see a setting that would auto hide/show any tabs that have zero games in them and then hide/show those when they have games in their tab again. 

This could show up as an "Hide when empty" toggle switch when making a new tab or a global toggle switch that effects all tabs in the main TabMaster menu.

**Comment by ArchaicBubba** [comment]
I'm a blind idiot ignore me

**Comment by jessebofill** [comment]
Yep it was implemented within last update.
