### ISSUE TITLE
[BUG]: Default tabs are gone

### ISSUE THREAD

**Issue by Laulajatar** [Tormak9970/TabMaster#156]
**Describe the bug**
All default tabs are gone. Only my custom tabs remain. This started with the update to 2.4. 
While I could recreate most of them with TabMaster, it's impossible to recreate the Collections tab.

**Logs**:
[2024-01-20 11.29.03.log](https://github.com/Tormak9970/TabMaster/files/13998534/2024-01-20.11.29.03.log)
[2024-01-20 11.29.02.log](https://github.com/Tormak9970/TabMaster/files/13998535/2024-01-20.11.29.02.log)

**Enviroment Info:**
 - SteamOS Version: 3.5.7
 - SteamOS Update Channel: Stable
 - Decky Version: 2.10.10
 - Decky Update Channel: Stable
 - TabMaster Version: 2.4.0-1

**Comment by Tormak9970** [comment]
> **Describe the bug** All default tabs are gone. Only my custom tabs remain. This started with the update to 2.4. While I could recreate most of them with TabMaster, it's impossible to recreate the Collections tab.
> 
> **Logs**: [2024-01-20 11.29.03.log](https://github.com/Tormak9970/TabMaster/files/13998534/2024-01-20.11.29.03.log) [2024-01-20 11.29.02.log](https://github.com/Tormak9970/TabMaster/files/13998535/2024-01-20.11.29.02.log)
> 
> **Enviroment Info:**
> 
>     * SteamOS Version: 3.5.7
> 
>     * SteamOS Update Channel: Stable
> 
>     * Decky Version: 2.10.10
> 
>     * Decky Update Channel: Stable
> 
>     * TabMaster Version: 2.4.0-1

can you share your settings.json too? We're looking into this

**Comment by Laulajatar** [comment]
Here: [settings.json](https://github.com/Tormak9970/TabMaster/files/13999046/settings.json)

Before the update, I only had one custom tab showing the contents of a collection, and reordered/hidden a few default tabs.

And thank you :)

**Comment by jessebofill** [comment]
> Here: [settings.json](https://github.com/Tormak9970/TabMaster/files/13999046/settings.json)
> 
> Before the update, I only had one custom tab showing the contents of a collection, and reordered/hidden a few default tabs.
> 
> And thank you :)

When you updated did you encounter any popup about having errors in some tabs and requiring you to fix them?

**Comment by Laulajatar** [comment]
> When you updated did you encounter any popup about having errors in some tabs and requiring you to fix them?

No, I didn't.

**Comment by jessebofill** [comment]
> > When you updated did you encounter any popup about having errors in some tabs and requiring you to fix them?
> 
> No, I didn't.

Ok and the default tabs were just gone immediately after updating?

**Comment by Laulajatar** [comment]
As far as I could tell. Before the update, it was broken for me as well, so I checked daily for 2.4 to arrive on stable, and when it did, I don't remember anything out of the ordinary while updating. Then I went to my library and everything but my one custom tab was gone.

![7_20240117172805_1](https://github.com/Tormak9970/TabMaster/assets/68446748/c3995232-b9ba-4b1b-8fce-b739f2b7a0a8)

While it was broken, I tried to (re)create a new tab which - I believe - would have had the same name as my existing one, since I wondered if perhaps just my config got nuked. Not sure if that would be relevant, as I don't see anything that shouldn't be there in the settings.json.

**Comment by jessebofill** [comment]
> As far as I could tell. Before the update, it was broken for me as well, so I checked daily for 2.4 to arrive on stable, and when it did, I don't remember anything out of the ordinary while updating. Then I went to my library and everything but my one custom tab was gone.
> 
> ![7_20240117172805_1](https://private-user-images.githubusercontent.com/68446748/298312890-c3995232-b9ba-4b1b-8fce-b739f2b7a0a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MDM3NzgsIm5iZiI6MTcwNTgwMzQ3OCwicGF0aCI6Ii82ODQ0Njc0OC8yOTgzMTI4OTAtYzM5OTUyMzItYjliYS00YjFiLThmY2UtYjczOWYyYjdhMGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDAyMTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMmI1MzEyY2Y4MzlkNjQ5NjU5MmEzOGI0YjJhNjhmZjkzMjUwYzkyMDU4YTg0MTM0OGU2Yjc4OTM2MDdkNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.phYqn_u2uiS_bY8XTsR4vcAlq8cISPDkVoxrz4ykf7c)
> 
> While it was broken, I tried to (re)create a new tab which - I believe - would have had the same name as my existing one, since I wondered if perhaps just my config got nuked. Not sure if that would be relevant, as I don't see anything that shouldn't be there in the settings.json.

Wait when you say “while it was broken” you mean while waiting for 2.4 release? How did you try to create a tab while it was broken?

**Comment by Laulajatar** [comment]
> Wait when you say “while it was broken” you mean while waiting for 2.4 release? How did you try to create a tab while it was broken? Did you try to edit the settings.json manually?

Yes, while waiting for 2.4 after the steamOS update broke it. No, the button to create new tabs was still there in the decky menu. The tab just never showed up. I never touched any config files or did anything outside the decky menu.

**Comment by jessebofill** [comment]
> > Wait when you say “while it was broken” you mean while waiting for 2.4 release? How did you try to create a tab while it was broken? Did you try to edit the settings.json manually?
> 
> Yes, while waiting for 2.4 after the steamOS update broke it. No, the button to create new tabs was still there in the decky menu. The tab just never showed up. I never touched any config files or did anything outside the decky menu.

Ok I think we may be on to something here. So you say after updating to 2.4, one and only one custom tab was there. Was this tab the same tab you tried to recreate while it was broken?

**Comment by Laulajatar** [comment]
> Ok I think we may be on to something here. So you say after updating to 2.4, one and only one custom tab was there. Was this tab the same tab you tried to recreate while it was broken?

It was, but I had only one (this) custom tab before, too. Other than that, I only used TabMaster to hide and reorder tabs.

**Comment by jessebofill** [comment]
> > Ok I think we may be on to something here. So you say after updating to 2.4, one and only one custom tab was there. Was this tab the same tab you tried to recreate while it was broken?
> 
> It was, but I had only one (this) custom tab before, too. Other than that, I only used TabMaster to hide and reorder tabs.

Ok it all makes sense now. while tab master was broken when you created a new tab it (your current tabs, including steam ones hadn't loaded) was still able to save that and overwrite the settings. I'll give you a fixed version of your settings.json in a sec.

**Comment by jessebofill** [comment]
Ok heres the fixed version of your settings.json with the steam tabs replaced. Now when you copy this file over in desktop mode you have to restart the deck immediately from desktop mode (don't go back into game mode or the settings in memory will just overwrite back). Alternatively you can uninstall tab master, copy settings in dekstop, go back to game mode, then reinstall tab master (this method you don't have to restart)

[settings.json](https://github.com/Tormak9970/TabMaster/files/14002168/settings.json)

**Comment by Laulajatar** [comment]
Thank you! It works :)

There's at least two other people on reddit with the same issue. Would suggesting to delete the settings.json and then reboot from desktop mode help them, assuming they are willing to recreate their custom tabs?

**Comment by jessebofill** [comment]
> Thank you! It works :)
> 
> There's at least two other people on reddit with the same issue. Would suggesting to delete the settings.json and then reboot from desktop mode help them, assuming they are willing to recreate their custom tabs?

You’re welcome, happy to help. Yeah that would be a good suggestion.

**Comment by jessebofill** [comment]
You can also refer them to reach out in our discord channel where I can also fix their settings if they want. https://discord.com/channels/960281551428522045/1049449185214206053

**Comment by Olenjan** [comment]
Same thing here. All defalt tabs are gone. But at least functions.

Plugin v2.4.0-1

Was able to recreate most of the defaults and custom, except for 'Collection' doesn't seem possible in 'gaming mode'

I had hidden the default tabs some previous version of steamOS and tabMaster

**Comment by Tormak9970** [comment]
This was fixed in the most recent update
