### ISSUE TITLE
[FLTR]: Exclude titles within a specific filter

### ISSUE THREAD

**Issue by W13N3N** [Tormak9970/TabMaster#157]
First off, thumbs up for this great project! It's truly amazing what this plugin already can do!

I'm trying to achieve something but i can't find a way how to do this. I've created a tab "All Games" with the filter "Installed". It also includes my external launchers (installed with nonsteamlaunchers) which i don't want because i want to add these to another tab.

So i want to exclude/remove these from the "installed" results. Is there an easy way to achieve this?

Thanks in advance!

**Comment by jessebofill** [comment]
There is the “Platform” filter which filters based on whether it is a steam or non steam app. You should be able to achieve what you want with this.
