### ISSUE TITLE
[BUG]: Broken on decky-loader v2.10.15-pre1 and SteamOS v3.5.14 beta/preview

### ISSUE THREAD

**Issue by videoman614** [Tormak9970/TabMaster#158]
**Describe the bug**
Plugin is broken on decky-loader v2.10.15-pre1 and SteamOS v3.5.14 beta/preview and needs to be updated.

**To Reproduce**
1. Update to SteamOS v3.5.14 beta/preview
2. Update to decky-loader v2.10.15-pre1 since 2.10.14 is broken on v3.5.14
3. Everything is broken, haha...

**Expected behavior**
Everything working as it was with decky-loader v2.10.14

**Screenshots**
![steamuserimages-a akamaihd](https://github.com/Tormak9970/TabMaster/assets/148925706/5ece3b45-a5b6-47c4-9541-78f915b4a7e6)

**Logs**:
[2024-02-04 21.02.19.log](https://github.com/Tormak9970/TabMaster/files/14156333/2024-02-04.21.02.19.log)

**Enviroment Info:**
 - SteamOS Version 3.5.14
 - SteamOS Update Channel Preview
 - Decky Version 2.10.15-pre1
 - Decky Update Channel Pre-release
 - TabMaster Version 2.4.0-1

**Comment by Tormak9970** [comment]
We'll take a look. If a decky update broke something then its possible this is s decky issue

**Comment by Pokepunch** [comment]
I think the issue is as below, this is being posted around on the Homebrew discord:
"Your plugin needs an DFL update.
Its not working anymore with latest SteamOS preview:
"Cannot read properties of undefined (reading "SimpleModal") error

Plugin authors should move to the global DFL to avoid having to bump the dependency."

**Comment by Tormak9970** [comment]
Yea, but we already use global dfl. We're looking into it

**Comment by videoman614** [comment]
Might be a SteamOS issue, some plugins are broken on decky-loader v2.10.15-pre1 and SteamOS v3.5.14 preview/beta but working fine on decky-loader v2.10.15-pre1 and SteamOS v3.5.7 stable.

**Comment by videoman614** [comment]
Seems to be working now.

Was away for new year so didn't check in.
