### ISSUE TITLE
[FLTR]: Ready to play (Locally installed OR streamable)?

### ISSUE THREAD

**Issue by philhzss** [Tormak9970/TabMaster#159]
Hi!

Perhaps the solution is just to press X in the library view to activate the built-in filter "Play State/Ready to Play", but I have a few tabs I use to show collections, and I'd like to have them show streamable games only if the PC that has them is turned on. Like, I need to have as filters the collection, AND (locally installed OR streamable). If that makes sense? Or just "ready to play", basically.

Do you think this is worth adding or should I just keep using Steam's built-in filter?

Thank you!

**Comment by Tormak9970** [comment]
> Hi!
> 
> 
> 
> Perhaps the solution is just to press X in the library view to activate the built-in filter "Play State/Ready to Play", but I have a few tabs I use to show collections, and I'd like to have them show streamable games only if the PC that has them is turned on. Like, I need to have as filters the collection, AND (locally installed OR streamable). If that makes sense? Or just "ready to play", basically.
> 
> 
> 
> Do you think this is worth adding or should I just keep using Steam's built-in filter?
> 
> 
> 
> Thank you!

Do a collection filter and then a merge group with (installed or streamable). Should give you what you want

**Comment by Tormak9970** [comment]
closing due to it already being possible and issue is now stale
