### ISSUE TITLE
[BUG]: Sd Card Option Grayed Out

### ISSUE THREAD

**Issue by NOTtanuki** [Tormak9970/TabMaster#165]
When navigating to the SD Card filter, it's grayed out and says that MicroSDeck 0.9.8 is needed but I installed MicroSDeck and its still not working, is it because I have the wrong version? If so, how do I get the 0.9.8 version?

**Comment by Tormak9970** [comment]
We're working on a for this, its because MircoSDeck hasn't hit 1.0 yet

**Comment by NOTtanuki** [comment]
Ah understandable, thanks!

**Comment by Tormak9970** [comment]
we've fixes this. it'll be included in the next release
