### ISSUE TITLE
[FLTR]: Implement "if" statements into group combination logic.

### ISSUE THREAD

**Issue by NOTtanuki** [Tormak9970/TabMaster#166]
This would most likely be viable in the group filter type (like merge group or something), an example of how this would be used is:

**IF**

––––––––––––––Merge Group––––––––––
Collection: Zombie Games
Whitelist: Days Gone
Installed: True
––––––––––––––––––––––––––––––––––––

**THEN/ELSE (Two Options)**

––––––––––––––Merge Group––––––––––
Whitelist: Days Gone 2
––––––––––––––––––––––––––––––––––––

This would give us the option to show games if a game is present on the steam deck or not. Think this could be used as a great alternative for the MicroSD option until it shows up and maybe even stuff that option can't do.

**Comment by Tormak9970** [comment]
Lets hear what @jessebofill has to say but imo this would be hard to implement, confuse a lot of users, and is already possible in most cases. Also I would personally consider it out of scope, but that's besides the point

**Comment by jessebofill** [comment]
I agree with tormak. Logically this would be very difficult to implement because it requires filters have dependencies on other filters which would be restricted by ordering or lead to circular dependencies and cause a lot of errors. Unfortunately I don’t think it’s possible.

**Comment by NOTtanuki** [comment]
Highly Understandable, just an idea for an alternative while we wait for the Micro SD card option to fully come out.
