### ISSUE TITLE
To be able to filter by MB in size not only GB

### ISSUE THREAD

**Issue by Endurions** [Tormak9970/TabMaster#167]
Hello. I would like to be able to filter away games that are smaller then 10 mb, but the smallest size is 1 GB or 0 GB. 

Could you make or add another bar where we can choose MB from 0 to 1 GB so if we have the GB bar at 0 and the MB bar at 10 MB it would remove only games smaller than 10 MB.

or if the GB was at 1 and MB at 200 it would sort away games under 1.2 GB

Or if it is easier,  just make a field where we can input an exact number in MB or bytes.

Ether way, 1 GB is to large for me to be able to sort out old games from newer smaller games.

Thanks for an otherwise great plug-in.

**Comment by Tormak9970** [comment]
@jessebofill we could prob make a dropdown for mb or gb right?

**Comment by Endurions** [comment]
Sounds good. :)

**Comment by jessebofill** [comment]
> @jessebofill we could prob make a dropdown for mb or gb right?

Yeah. I mean it would be easier to just make it finer resolution instead of adding another parameter. But whatever you wanna do.

**Comment by Tormak9970** [comment]
> > @jessebofill we could prob make a dropdown for mb or gb right?
> 
> 
> 
> Yeah. I mean it would be easier to just make it finer resolution instead of adding another parameter. But whatever you wanna do. 

Yea good point, that's prob a better solution anyways

**Comment by Tormak9970** [comment]
this has been implemented as of https://github.com/Tormak9970/TabMaster/commit/f5eb62dcafdf3bd60ed5431d2a828e33e4df9a8e. It will be included in the next release
