### ISSUE TITLE
[FLTR]: Filtering by earned achievements number / percentage

### ISSUE THREAD

**Issue by pawel-ch** [Tormak9970/TabMaster#168]
Hi, I would like to have a tab which consist of the games matching the following criteria:

- At least one achievement was earned
- At least one achievement is missing (less than 100% unlocked)

This would greatly help with focusing on ending games first and would also help in removing removing completed games from the list.

The best thing that can be done for now is sorting by achievement percentage descending, but it has a big con that you have to scroll a while to reach first not completed game.

Another approach could be introducing negative filters, so for example "exclude all completed games" and/or "exclude all games with no achievements earned".

**Comment by Tormak9970** [comment]
I think this is a great idea. I need to play around with what it would look like, but its definitely doable

**Comment by Tormak9970** [comment]
this has been implemented as of https://github.com/Tormak9970/TabMaster/commit/f7499e01a4c68a5be17dad03435b1f6886ede143. It will be included in the next release.

**Comment by pawel-ch** [comment]
That's great, thank you @Tormak9970 for a quick implementation. I've read the linked commit and what worries me is the `>=` and `<=` in filter.

With implementation like that we won't be able to precisely set filters to be >0% and <100% so we won't be able to exclude games with no achievements earned and with 100% achievements earned.

Even if I set 1% or above then for games like [Zaccaria Pinball](https://store.steampowered.com/app/444930/Zaccaria_Pinball/) with 4820 achievements, when you unlock your first achievement the game won't be shown in such a list (because the completion will be ~0.02%). Using the same game as example, when you have 4819 a out of 4820 achievements you can encounter the same problem with 99% and below filter.

Another issue is rounding – I wouldn't be surprised if 0,02% and 99,979% were interpreted as 0% and 100% respectively.

I think the easiest fix would be to include 4 options in the dropdown:
- At least (>=)
- More than (>)
- At most (<=)
- Less than (>)

I wouldn't remove existing options as someone could find it valuable to set it as >=50% or any other pretty number.

**Comment by Tormak9970** [comment]
< 100% can be achieved by =< 99% and > 0% can be achieved by => 1% I believe

**Comment by pawel-ch** [comment]
Hi, I've tested the newly released version and noticed, that even though I have 63 out of 68 achievements unlocked (93%) for [Froguelike](https://store.steampowered.com/app/2315020/Froguelike/) it doesn't appear, when using new filters.

I have 2 related tabs at the moment:
- `>=0 AND <=99` – this is where I expected this game to show up
- `>-0 AND <=50`

**Comment by pawel-ch** [comment]
Creating the tab from scratch haven't changed anything. Maybe I'll try to setup React Developer Tools on the weekend to take a look at the available variables and see what's different about this game. I wonder if the filters will work with non-steam emulated games with Retro Achievements.

**Comment by Tormak9970** [comment]
> Creating the tab from scratch haven't changed anything. Maybe I'll try to setup React Developer Tools on the weekend to take a look at the available variables and see what's different about this game.
> 
> 
> 
> Aside from that I wonder if the filters will work with non-steam emulated games with Retro Achievements – maybe I'll look into it as well.

Probably wont work with them as we're using a built in steam function to get completion percentage, but there's a chance it does

**Comment by Tormak9970** [comment]
@pawel-ch We've added a `count` option which should address the issue of filtering by at least X achievements https://github.com/Tormak9970/TabMaster/commit/ab3fd6b02a7950de3e7eedc20283a2db9c5cc1af

**Comment by pawel-ch** [comment]
Thank you, I wanted to test it, but the latest version of TabMaster in Decky marketplace is 2.5.5.

**Comment by Tormak9970** [comment]
> Thank you, I wanted to test it, but the latest version of TabMaster in Decky marketplace is 2.5.5.

This will be included in the next release, 2.7.0

**Comment by pawel-ch** [comment]
Oh, it's on `dev` branch. I thought it was in 2.6.0 already (which I still don't see in marketplace). I guess I'll build and install it manually ;-)

**Comment by pawel-ch** [comment]
I've checked it and the count option looks nice for "at least", but makes no sense for "at most". For example "at most count 100" for Zaccaria Pinball doesn't really tell you anything, when this game has so many achievements.

It looks that you solved the gap between 0% and 1%, the gap between 99% and 100% remains and there's still no way to exclude 100%, but keep 99,99999%.

**Comment by Tormak9970** [comment]
> I've checked it and the count option looks nice for "at least", but makes no sense for "at most". For example "at most count 100" for Zaccaria Pinball doesn't really tell you anything, when this game has so many achievements.
> 
> 
> 
> It looks like you have solved the gap between 0% and 1%, the gap between 99% and 100% remains and there's still no way to exclude 100%, but keep 99,99999%.
> 
> 
> 
> Edit:
> 
> Wow, I've got it! Achievements, invert, at least 100% or more completed gives me exactly what I want.

Glad to hear it. Yea it has to have an upper limit, and you can achieve your goal via inversion
