### ISSUE TITLE
[FEAT]: Default Sort Setting for Tab

### ISSUE THREAD

**Issue by vrokolos** [Tormak9970/TabMaster#184]
Can we link sort order with each tab in the future?
I want to create a tab: All Games by release date
another one: All games by score
and many other similar cases

**Comment by Tormak9970** [comment]
> Can we link sort order with each tab in the future?
> 
> I want to create a tab: All Games by release date
> 
> another one: All games by score
> 
> and many other similar cases

Like automatically apply the specified sorting method for the tab?

**Comment by vrokolos** [comment]
yes

**Comment by Tormak9970** [comment]
> yes

We can look into that

**Comment by Tormak9970** [comment]
@jessebofill Thoughts on this? I've looked into it and I can't seem to find a way to hook into when the current tab changes

**Comment by jessebofill** [comment]
Default tabs use a global sorting and it’s not able (easily) to modify that. I’ve tried before. So individual sorting per tab only on custom tabs would kinda be incoherent behavior.

**Comment by Tormak9970** [comment]
> Default tabs use a global sorting and it’s not able (easily) to modify that. I’ve tried before. So individual sorting per tab only on custom tabs would kinda be incoherent behavior. 

Yea that makes sense. Also it would reset the chosen filter every time you switched tabs which is kind of annoying

**Comment by Tormak9970** [comment]
@vrokolos Closing this for now, we may revisit it in the future if we have a good solution
