### ISSUE TITLE
[FEAT]: Windows (Steam Big Picture) port for TabMaster

### ISSUE THREAD

**Issue by lyndonguitar** [Tormak9970/TabMaster#186]
Honestly, in terms of Library management, I am finding my Steam Deck is way superior over my Windows PC because of TabMaster. And I whenever I use my PC for Big Picture mode, I always remember how awesome TabMaster is and how I wish I had it to manage the tabs. Especially when dealing with Non-Steam titles.

Currently, there is a workaround for DeckyLoader (which is used by TabMaster) to be installed on Windows to run some plugins(see the next link below), but in my limited testing, running TabMaster there unfortunately doesn't work.

https://www.reddit.com/r/WindowsOnDeck/comments/17gzzvq/comment/k7b1p02/

Another glimmer of hope is a standalone release for windows like what CSSLoader pulled off here below
https://github.com/DeckThemes/CSSLoader-Desktop/releases

**Comment by Tormak9970** [comment]
I can look into this

**Comment by Tormak9970** [comment]
closing this as the latest version of tabmaster does work on windows
