### ISSUE TITLE
[FLTR]: Filtering by Steam Family Sharing games

### ISSUE THREAD

**Issue by L1Z3** [Tormak9970/TabMaster#187]
It would be very useful to be able to filter games that are in my library through Steam Family Sharing (or, its replacement, Steam Families). That is, I'd like to be able to filter games that are tagged as "From your Steam Family library". 

If possible, it would also be nice to be able to filter based on which people in my Steam Family are sharing the game with me. Maybe this could be achieved through this API function https://steamapi.xpaw.me/#IFamilyGroupsService/GetSharedLibraryApps

**Comment by Tormak9970** [comment]
We can look into it. Prob wouldn't be through that api function because we have direct access to the steam client when injected via decky, but thanks for the starting point!

**Comment by Tormak9970** [comment]
This has been implemented and will be available in v2.6.0. For now filtering by the member who shares it with you is not possible, but we will continue to look into that as Steam polishes the feature

**Comment by L1Z3** [comment]
Great, thanks so much!
