### ISSUE TITLE
[BUG]: "Home" section of "Settings" doesn't work with this plugin installed

### ISSUE THREAD

**Issue by Daeymon** [Tormak9970/TabMaster#188]
"Home" section of "Settings" doesn't work with this plugin installed.
![steamuserimages-a akamaihd](https://github.com/Tormak9970/TabMaster/assets/29780145/844b2072-cb21-4cf6-b521-d3eb2a0fed90)

Can be easily reproduced with a clean installation of DeckyLoader and only having TabMaster installed. Uninstalling TabMaster resolves the issue.

[2024-06-15 18.17.54.log](https://github.com/user-attachments/files/15849150/2024-06-15.18.17.54.log)

 - SteamOS Version: 3.5.19 (Build 20240422.1)
 - SteamOS Update Channel: Stable
 - Decky Version: 2.12.3
 - Decky Update Channel: Stable
 - TabMaster Version: 2.5.4 (have also tried 2.5.4-7b9474b)

**Comment by Tormak9970** [comment]
fixed with https://github.com/Tormak9970/TabMaster/commit/873125f7f379e6f8bb215c542bb280f04d6ee184. Will make a database pr asap

**Comment by Daeymon** [comment]
This issue is back after the latest update of the plugin

**Comment by jessebofill** [comment]
@Tormak9970 i briefly tested and looks like it breaks on stable client but not beta.

**Comment by Tormak9970** [comment]
I was afraid this might happen. The testers probably didn't have any hidden games when they tested on stable

**Comment by jessebofill** [comment]
Should be a simple fix at least. I can look into it tomorrow unless you get to it earlier.

**Comment by Tormak9970** [comment]
> Should be a simple fix at least. I can look into it tomorrow unless you get to it earlier. 

Issue is pushing the fix out would break beta without a bunch of conditional logic, but ig we'll have to do that for now

**Comment by jessebofill** [comment]
Yeah true. Hopefully it’s not too bad

**Comment by Tormak9970** [comment]
We fixed this issue, make sure to install the testing store version
