### ISSUE TITLE
[BUG]: Not functional in SteamOS 3.6.8

### ISSUE THREAD

**Issue by NBOOK** [Tormak9970/TabMaster#192]
**Describe the bug**
In QAM --> TabMaster, "Add Tab" is grayed out and the "TABS" shows loading forever.

**To Reproduce**
1. Upgrade the OS to 3.6.8 (beta)
2. Install the latest prerelease decky-loader (v3.0.0-pre1)
4. Install the latest TabMaster (v2.5.6) from zip
5. Open TabMaster in QAM

**Expected behavior**
Can manage the tabs

**Screenshots**
![20240627031909_1](https://github.com/Tormak9970/TabMaster/assets/16967347/7042b12f-dbe8-4d93-92d4-b413660bf5a2)

**Logs**:
[TabMaster.zip](https://github.com/user-attachments/files/16009892/TabMaster.zip)

**Enviroment Info:**
 - SteamOS Version: 3.6.8
 - SteamOS Update Channel: Beta
 - Decky Version: v3.0.0-pre1
 - Decky Update Channel: Prerelease
 - TabMaster Version: 2.5.6

**Comment by loganjchris** [comment]
Reinstalling from the plugins tab of decky settings causes a memory leak. I'm not sure if this is a tap Master problem or a decky loader problem?

**Comment by Tormak9970** [comment]
> Reinstalling from the plugins tab of decky settings causes a memory leak. I'm not sure if this is a tap Master problem or a decky loader problem?

I've had other users report this as well. Does it occur with other plugins?

**Comment by Memenado** [comment]
> I've had other users report this as well. Does it occur with other plugins?

Have tested 2 others and gotten a successful reinstall, seems to just be TabMaster

**Comment by Tormak9970** [comment]
> > I've had other users report this as well. Does it occur with other plugins?
> 
> 
> 
> Have tested 2 others and gotten a successful reinstall, seems to just be TabMaster

Ok good to know. Which plugins did you test reinstalling? Issue might be TabMaster doesn't have an _uninstall hook because that's a new decky feature

**Comment by jessebofill** [comment]
> Reinstalling from the plugins tab of decky settings causes a memory leak. I'm not sure if this is a tap Master problem or a decky loader problem?

Can you be more specific about this? How have you determined a memory leak? And I don’t think this is related to op issue

**Comment by jessebofill** [comment]
@Tormak9970 ive quickly tested and as for op issue I think the something might have changed with the apps map. As for reinstalling I’m not sure what the others are referring to but it works for me

**Comment by Tormak9970** [comment]
Shit. 3.6.8 already broke the tags object (which is now fixed), but they must have changed apps since yesterday morning lol. You want to look into it? I'll try to push out a fix later if not

**Comment by jessebofill** [comment]
Yeah I’ve got some time to take a look

**Comment by Tormak9970** [comment]
@NBOOK fixed as of https://github.com/Tormak9970/TabMaster/commit/01fa79f50ce339f43d1ee210479c3973ee3a95df. Will be included in 2.6.0 (we will have to wait until these changes come to stable to release it, but we will make a standalone release once additional things are done)

**Comment by Sythog** [comment]
@Tormak9970 any ETA on 2.6.0 showing up in the Decky store?

**Comment by Tormak9970** [comment]
> @Tormak9970 any ETA on 2.6.0 showing up in the Decky store?

No unfortunately. Hopefully it will be soon but we need to finish a few things and then it will have to go under review
