### ISSUE TITLE
[FEAT]: Order ítems on tabs

### ISSUE THREAD

**Issue by algonal9** [Tormak9970/TabMaster#196]
To be able to sort the games within a tab by date in which it is added to the library without affecting the rest of the tabs.

**Comment by Tormak9970** [comment]
This is similar to https://github.com/Tormak9970/TabMaster/issues/184, however I have an idea that may work, we'll look into this

**Comment by jessebofill** [comment]
@Tormak9970 maybe we could just add a toggle for custom tabs (per tab) whether it should use global sorting or only itself
