### ISSUE TITLE
[FEAT]: Integration with Emuchievements

### ISSUE THREAD

**Issue by pawel-ch** [Tormak9970/TabMaster#198]
Now that we have filtering by achievement counts/percentages (https://github.com/Tormak9970/TabMaster/issues/168) maybe there's a chance to add Retro Achievements support by some kind of integration with https://github.com/EmuDeck/Emuchievements?

**Comment by Tormak9970** [comment]
@KP2048 can you confirm if you modify the achievements store with EmuAchievements? I recall you mentioning something similar to that

**Comment by KP2048** [comment]
Yes I do

**Comment by pawel-ch** [comment]
OK, I see why they weren't there. I've got the additional filter "games installed locally" set in my tab and the non-steam games were excluded because of that – which is strange.

**Comment by KP2048** [comment]
I modify `appAchievementProgressCache`, i also patch some things that aren't global

**Comment by KP2048** [comment]
MetaDeck also patches the deck verified thing so filtering by that should also work

**Comment by pawel-ch** [comment]
I guess you can close this issue. Fastest implementation ever :grin: 

I've replaced "Collection: installed locally" filter with "Installed" and it works like a charm.
