### ISSUE TITLE
[FLTR]: Filter by installed order by install date

### ISSUE THREAD

**Issue by algonal9** [Tormak9970/TabMaster#199]
Filter games by installed, order by install date and  that I can select number of data.

**Comment by Tormak9970** [comment]
> Filter games by installed, order by install date and  that I can select number of data.

Can you elaborate? We already have an installed/uninstalled filter. Are you asking about an install date filter?

**Comment by algonal9** [comment]
I was referring to a filter that showed you the games installed for example the last 10 days but ordered by setup date.

**Comment by Tormak9970** [comment]
> I was referring to a filter that showed you the games installed for example the last 10 days but ordered by setup date.

Alright. Those will be two different things, a filter by install date and a sorting method for tabs (what we're working on rn). Not sure if install date is tracked but I'll look into it

**Comment by Tormak9970** [comment]
Included as of https://github.com/Tormak9970/TabMaster/releases/tag/v2.7.0
