### ISSUE TITLE
[BUG]: Stuck Loading

### ISSUE THREAD

**Issue by CreeperofDoom** [Tormak9970/TabMaster#200]
**Describe the bug**
Tabmaster is broken on the latest Steam Deck Beta, it remains Stuck on Loading no matter if i reinstall Tabmaster, i also tried instaling Tabmaster via the Testing Decky Story and that one doesn’t work at all…

**To Reproduce**
1. Have Tabmaster Installed
2. Be on the latest Beta recording update
3. Open the Quick Access Menu
4. Head to Decky Loader and press Tabmaster

**Expected behavior**
Expected Tabmaster to work as it did prior with all my Custom tabs and tabs i removed

**Screenshots**
![A5B51D50-BB07-45DC-9E5F-F0544FAAA525](https://github.com/Tormak9970/TabMaster/assets/34628285/c3d7f8af-977c-4fba-8d1f-3cdff269e7c2)

**Logs**:
The log file should be found at `~/homebrew/logs/TabMaster/TabMaster.log`

**Enviroment Info:**
 - SteamOS Version 3.6.8
 - SteamOS Update Channel: BETA
 - Decky Version: v3.0.0-pre4
 - Decky Update Channel: Prerelease
 - TabMaster Version: 2.5.5

**Comment by Tormak9970** [comment]
please see #192. You can install the standalone release for 2.6.0 to fix this

**Comment by Tormak9970** [comment]
making a decky database PR to move this to the testing store now
