### ISSUE TITLE
[BUG]: Unable to select tags for tag filter

### ISSUE THREAD

**Issue by Steggers** [Tormak9970/TabMaster#201]
**Describe the bug**
I attempted to use the tag filter however it does not allow you to interact with the tag selection. You can highlight it but not interact with it. 

**To Reproduce**
1. Creat new tab
2. Set filter to tag
3. Attempt to interact with tag selector

**Expected behavior**
A searchable list of tags to filter by. 

**Enviroment Info:**
 - SteamOS Version 3.5.19
 - SteamOS Update Channel  Stable
 - Decky Version 2.12.3
 - Decky Update Channel Stable
 - TabMaster Version 2.5.5

As a side note, this is my first time trying TabMaster and I may be misunderstanding how to use the filter.

**Comment by Tormak9970** [comment]
fix is included in v2.70 https://github.com/Tormak9970/TabMaster/releases/tag/v2.7.0
