### ISSUE TITLE
[FEAT]: Windows Support

### ISSUE THREAD

**Issue by ntcrft** [Tormak9970/TabMaster#204]
Decky-Loader has a WIP port for Windows and unfortunately it doesn't seem like TabMaster works quite yet (it gets stuck loading in an endless loop). A potential patch or fork for Windows would be appreciated!

**Comment by Tormak9970** [comment]
> Decky-Loader has a WIP port for Windows and unfortunately it doesn't seem like TabMaster works quite yet (it gets stuck loading in an endless loop). A potential patch or fork for Windows would be appreciated!

You need to install v2.7.0 if you're on the steam client beta. The windows build should also work fine, its just not official because Decky is aimed at the deck. Lmk if there's still issues after trying the new version

**Comment by ntcrft** [comment]
When opening the TabMaster menu from QAM it just gets stuck on loading the tabs and the option to add new tabs is greyed out.

OS: Windows 11 24H2
Steam version: 1722380543 (Beta)
TabMaster version: 2.7.0

I also tried reverting steam to the latest stable version, same loading loop occured.

**Comment by ntcrft** [comment]
Seems like the latest Decky Loader beta fixes the loading issues and makes the plugin work as intended. Closing this issue.
