### ISSUE TITLE
[BUG]: Tabmaster crashes Decky Loader when accessing Steam Deck settings

### ISSUE THREAD

**Issue by Kaympe20** [Tormak9970/TabMaster#205]
**Describe the bug**
Upon opening my Steam Deck settings, Decky Loader informs me that it has crashed due to an issus in Tabmaster.

**To Reproduce**
1. Download Tabmaster
2.  Go to Settings
3. See error

**Screenshots**
![PXL_20240807_155445188](https://github.com/user-attachments/assets/a3af9d70-0e86-4fa7-bb69-f6cbec1dda15)
![PXL_20240807_155535412](https://github.com/user-attachments/assets/a2a14b11-db5e-45a9-bf7d-62e3d3e585b7)
![PXL_20240807_155621319](https://github.com/user-attachments/assets/b37e632a-1010-4ab5-8aff-f4235a900412)
![PXL_20240807_155630431](https://github.com/user-attachments/assets/7368a8cb-14ae-4702-a008-bc85ff6f886b)

**Logs**:
[2024-08-07 11.53.33.log](https://github.com/user-attachments/files/16531360/2024-08-07.11.53.33.log)

**Enviroment Info:**
 - SteamOS Version: 3.6.8
 - SteamOS Update Channel Beta
 - Decky Version V3.0.0-pre6
 - Decky Update Channel Pre-release
 - TabMaster Version 2.5.5

**Comment by Tormak9970** [comment]
@Kaympe20 thank you for the detailed report. I believe this will be fixed by installing v2.7.0. It should be available on the testing store now, and if not you can install the zip here: https://github.com/Tormak9970/TabMaster/releases/tag/v2.7.0. Let us know if the issue persists

**Comment by Kaympe20** [comment]
@Tormak9970 How do you install a plugin manually?

**Comment by Tormak9970** [comment]
1. In Desktop mode, pull up https://github.com/Tormak9970/TabMaster/releases/tag/v2.7.0 in your steam deck's browser (if you use firefox you can just send the tab to your steamdeck so you don't have to type in the browser)
2. Download the .zip and put it somewhere easy to find (I'd recommend your desktop)
3. In Game Mode, go to Decky's settings and choose the install from zip option
4. Navigate to where you downloaded the zip and choose it

**Comment by Kaympe20** [comment]
@Tormak9970 Where is the install from zip option?

**Comment by Tormak9970** [comment]
I forgot its in the developer tab. You'll have to enable decky's developer mode, which is in the General tab
