### ISSUE TITLE
[BUG]: Multiple "Uncaught (in promise)" TypeErrors while plugin is loading in SteamOS Beta

### ISSUE THREAD

**Issue by eXhumer** [Tormak9970/TabMaster#216]
**Describe the bug**
On SteamOS 3.6.17 (latest beta version of Steam at time of writing), throws two "Uncaught (in promise)" errors in CEF console during the plugin loading phase.

**To Reproduce**
1. Install latest SteamOS beta (3.6.17).
2. Load Decky Loader with plugin installed.
3. Check CEF console in Decky Loader developer section.

**Expected behavior**
No errors from plugin while loading.

**Screenshots**
![20241008130518_1](https://github.com/user-attachments/assets/cd0dba78-cbb0-4b45-b07b-ecaf82ddf359)

**Logs**:
The log file should be found at `~/homebrew/logs/TabMaster/TabMaster.log`

**Enviroment Info:**
 - SteamOS Version: 3.6.17
 - SteamOS Update Channel: Beta
 - Decky Version: v3.0.2-pre2
 - Decky Update Channel: Pre-release
 - TabMaster Version: 2.7.0

**Comment by Tormak9970** [comment]
I'll look into this when I get a chance, I think the plugin is fully broken on beta atm

**Comment by eXhumer** [comment]
> I think the plugin is fully broken on beta atm

I don't think that is the case. These errors only appear on logs. The plugin seems to function on the latest SteamClient beta (1731433018), released on 11th November just fine.

**Comment by Tormak9970** [comment]
Huh, thought it broke for me on beta, either way I'll look into this

**Comment by jessebofill** [comment]
was caused by change to friend store entries.
