### ISSUE TITLE
[BUG]: Is installed filter is reversed

### ISSUE THREAD

**Issue by picknassaro** [Tormak9970/TabMaster#217]
**Describe the bug**
Installed filter is erroneously inversed.

**To Reproduce**
1. Create a new tab or edit a tab
2. Add an “Installed” filter
3. Turn the toggle for “Is installed?” on
4. Uninstalled games will appear instead of installed games

**Expected behavior**
When enabling installed games, installed games should be shown. When disabling installed games, games that are not installed should be shown.

**Enviroment Info:**
 - SteamOS Version 3.6.19
 - SteamOS Update Channel Stable
 - Decky Version 3.0.1
 - Decky Update Channel Stable
 - TabMaster Version 2.7.2

**Comment by jessebofill** [comment]
Hmm I don’t experience this. Maybe you are confusing this with non steam games? Because steam automatically considers those installed, so they will also show up with this filter.

**Comment by Tormak9970** [comment]
I also haven't experienced this. As @jessebofill said, sounds like non-steam games to me

**Comment by Tormak9970** [comment]
Closing this as we can't reproduce it. @picknassaro if this is still an issue can you provide more details such as what games are showing up, other plugins installed, etc?
