### ISSUE TITLE
[FLTR]: Family sharing filter: Option to specify specific family member.

### ISSUE THREAD

**Issue by Cleover** [Tormak9970/TabMaster#220]
Currently in the family sharing filter you only have the option for "Is from a family member?"

It would be nice to be able to specify which family member to show games from if this is possible to fetch.

(This kinda goes alongside my other sub tab feature request)
To make it so I could have sub tabs for my "Family Sharing" tab like:

Default (all)
\<Family Mem 1>
\<Family Mem 2>
\<etc>

**Comment by jessebofill** [comment]
We tried to do this when we first implement the filter but unfortunately with the way steam handles family shared games there’s not a feasible way to do it.

**Comment by Cleover** [comment]
Ah shame

Does steam make it easy to get a list of games a specific friend owns (if it's public)?

Would it instead be possible to have an extra filter for "owned by" where it only shows games that the selected friend owns?

(There is a similar filter but it works where it shows games you and that friend own, rather then games that the friend owns that you don't)

Obviously it wouldn't show games you don't have access to, however it could maybe be used to filter out the family share list perhaps?

**Comment by jessebofill** [comment]
They’re effectively the same thing. all filters operate on the list of games that are in your library ie games you “own”. So even the family shared games steam considers that you own those games.

**Comment by Tormak9970** [comment]
we'll revisit this if we discover a way to do this
