### ISSUE TITLE
[FEAT]: Built in docs page, similar to Bash Shortcuts

### ISSUE THREAD

**Issue by Tormak9970** [Tormak9970/TabMaster#23]
Once more complex filters and combinations are added, it may be beneficial to readable guides in SteamOS like I've done in Bash Shortcuts.

**Comment by jessebofill** [comment]
Isn’t decky planning this functionality built in?

**Comment by Tormak9970** [comment]
TODO: switch branch for image src to master once testing is done

**Comment by Tormak9970** [comment]
complete as of https://github.com/Tormak9970/TabMaster/commit/bb5434ccecc02d50f195aad9150a5d7a5f58d7ca
