### ISSUE TITLE
[FEAT]: Global "and" "or"

### ISSUE THREAD

**Issue by Tormak9970** [Tormak9970/TabMaster#24]
Like how tags and friends work, this would apply to all listed filters. An expansion on this would be to all the setting for individual groups (essentially full boolean logic)

**Comment by jessebofill** [comment]
i've got the pretty much all the functionality for this done, just need to add a setting to the modal. and this implementation should allow to easily expand it to full boolean logic, the tricky part for this is how to expose it to the user, but i have some ideas

**Comment by Tormak9970** [comment]
> i've got the pretty much all the functionality for this done, just need to add a setting to the modal. i also pretty much have it ready for grouping and applying boolean ops between groups, the tricky part for this is how to expose it to the user, but i have some ideas

Awesome. Yea, exposing it to the user may prove a bit challenging

**Comment by Tormak9970** [comment]
complete as of https://github.com/Tormak9970/TabMaster/commit/859a8ac7ec7f0e37b1a37fe6cb0bfc0024c0a9c5
