### ISSUE TITLE
[FEAT]: Manual Blacklist/Whitelist

### ISSUE THREAD

**Issue by Tormak9970** [Tormak9970/TabMaster#25]
Provide users the ability to blacklist and whitelist individual games for a tab. Can use the patching in Decky-SAM for the context menu, and have it show up when editing the tab

**Comment by jessebofill** [comment]
What’s Decky-SAM?

**Comment by Tormak9970** [comment]
> What’s Decky-SAM?

Another plugin of mine

**Comment by jessebofill** [comment]
This should also be considered a filter internally.

**Comment by Tormak9970** [comment]
it will. It will just also have the context menus for convenience/native feel

**Comment by jessebofill** [comment]
hmm, but whitelist/ blacklist will have to know which tab is open when patching game context menu. i think we can just look the route, it should include currently open tab

**Comment by Tormak9970** [comment]
filter logic complete as of https://github.com/Tormak9970/TabMaster/commit/4aa0a948e45e471d761e5c3a969563c5a69866ca
