### ISSUE TITLE
[FEAT]: Add filter for game properties

### ISSUE THREAD

**Issue by Tormak9970** [Tormak9970/TabMaster#26]
This will require some work on figuring out what should be filterable by. having any seems too complicated.

**Comment by jessebofill** [comment]
What are game properties

**Comment by Tormak9970** [comment]
> What are game properties

Like properties on the gameOverview type

**Comment by jessebofill** [comment]
> > What are game properties
> 
> Like properties on the gameOverview type

Oh I haven’t looked at that before

**Comment by Tormak9970** [comment]
I'm thinking of scrapping this. Most of the props already have filters, and it would be an extremely convoluted system for not a lot of gain

**Comment by jessebofill** [comment]
> I'm thinking of scrapping this. Most of the props already have filters, and it would be an extremely convoluted system for not a lot of gain

yeah i think thats fine
