### ISSUE TITLE
Is it possible to auto focus filter selection dropdown when clicking add fillter?

### ISSUE THREAD

**Issue by jessebofill** [Tormak9970/TabMaster#28]
Ideally when the add filter button is clicked the filter type selection would automatically be focused. Now this is a rhetorical question because i know it's possible and also that it's quite annoying to do, but maybe we could look into it and find a simple way.

**Comment by Tormak9970** [comment]
> Ideally when the add filter button is clicked the filter type selection would automatically be focused. Now this is a rhetorical question because i know it's possible and also that it's quite annoying to do, but maybe we could look into it and find a simple way.

lol it should literally be `element.focus()` nice and easy

**Comment by Tormak9970** [comment]
At one point, something like what I said was possible, might have changed though

**Comment by jessebofill** [comment]
well hopefully it is, we'll look into it
