### ISSUE TITLE
[UPKEEP]: Add editorconfig, .vscode workspace settings, commitlint, and prettier

### ISSUE THREAD

**Issue by Tormak9970** [Tormak9970/TabMaster#32]
No rush, but right now our styling and commit syntax is not enforced whatsoever. While I think we have both done a great job, would be nice to be able to auto format and verify that we don't accidentally let a malformed commit slide through

**Comment by jessebofill** [comment]
ok. i'm not familiar with best practices in this regard. i've just been trying to follow your lead, but if there's autocheckers then that would help.

**Comment by Tormak9970** [comment]
Complete as of https://github.com/Tormak9970/TabMaster/commit/08ba76785b49edb122e678f7b2e633105e3e365b. Also added contribution guidelines and recommended extensions
