### ISSUE TITLE
[BUG]: Favourites collection not working

### ISSUE THREAD

**Issue by VioletStorm** [Tormak9970/TabMaster#36]
**Describe the bug**
Setting a custom tab to include favourites collection shows nothing

**To Reproduce**
1: Create new custom tab set to collections: favourites
2: View new tab

**Expected behavior**
All favourited games are shown

**Screenshots**
![Screenshot_20230630-223745 (1).png](https://github.com/Tormak9970/TabMaster/assets/54405427/4cb83f66-57dc-421c-acbe-a371f3a256df)
![Screenshot_20230630-223631 (1).png](https://github.com/Tormak9970/TabMaster/assets/54405427/575d389d-3463-4a19-a6e2-e017d475f264)

**Enviroment Info:**
 - SteamOS Version: 3.4.8 
 - SteamOS Update Channel: Beta
 - Decky Version: 2.10.1
 - Decky Update Channel: Stable
 - TabMaster Version: 1.1.2-d2bf5dc

**Comment by jessebofill** [comment]
Thanks for the heads up. Issue is fixed.
