### ISSUE TITLE
[FEAT]: Rename Official Tabs

### ISSUE THREAD

**Issue by VioletStorm** [Tormak9970/TabMaster#37]
**Is your feature request related to a problem? Please describe.**
If someone were to want to rename the preexisting tabs, they currently can't

**Describe the solution you'd like**
An option to edit the name of existing official tabs

**Comment by Tormak9970** [comment]
@VioletStorm Can't this be achieved by making a custom tab with the same/similar filters to a default one?

**Comment by VioletStorm** [comment]
> @VioletStorm Can't this be achieved by making a custom tab with the same/similar filters to a default one?

Well this is true to an extent, but it takes a lot more steps yeah? Plus that means you have to hide the default ones which adds clutter, and also one or two of the defaults are especially difficult to get with editing the filters.

Idk, just think it would be nice qol to have a little edit button on default tabs too that just had a rename option

**Comment by Tormak9970** [comment]
> > @VioletStorm Can't this be achieved by making a custom tab with the same/similar filters to a default one?
> 
> Well this is true to an extent, but it takes a lot more steps yeah? Plus that means you have to hide the default ones which adds clutter, and also one or two of the defaults are especially difficult to get with editing the filters.
> 
> Idk, just think it would be nice qol to have a little edit button on default tabs too that just had a rename option

Hmm, its a valid point, however it would require a rework of how we handle default tabs, and contradicts the idea of "default" imo. However, I will leave this issue open for now, and if there is significant interest in this idea, we'll reconsider

**Comment by VioletStorm** [comment]
> > > @VioletStorm Can't this be achieved by making a custom tab with the same/similar filters to a default one?
> > 
> > Well this is true to an extent, but it takes a lot more steps yeah? Plus that means you have to hide the default ones which adds clutter, and also one or two of the defaults are especially difficult to get with editing the filters.
> > 
> > Idk, just think it would be nice qol to have a little edit button on default tabs too that just had a rename option
> 
> Hmm, its a valid point, however it would require a rework of how we handle default tabs, and contradicts the idea of "default" imo. However, I will leave this issue open for now, and if there is significant interest in this idea, we'll reconsider

That's all I can ask! ☺️ Cheers!

**Comment by Tormak9970** [comment]
Closing this as there has not been much interest and this is achieveable by replacing the recreating default tab using a custom one
