### ISSUE TITLE
[BUG]: After installing the plugin, system settings do not open

### ISSUE THREAD

**Issue by free-storage** [Tormak9970/TabMaster#46]
**Describe the bug**
After installing the plugin, system settings do not open.

**To Reproduce**
1. Install plugin from Decky
2. Click on Settings in left menu
3. Crash (screenshot)

**Screenshots**
![2023-07-04 00 00 34](https://github.com/Tormak9970/TabMaster/assets/52704675/8ae80b9f-8faa-455b-ad42-a3c14ebd1697)

**Enviroment Info:**
 - SteamOS Version [last stable]
 - SteamOS Update Channel [Stable]
 - Decky Version [last stable]
 - Decky Update Channel [Stable]
 - TabMaster Version [last]

**Comment by Tormak9970** [comment]
> **Describe the bug**
> After installing the plugin, system settings do not open.
> 
> **To Reproduce**
> 1. Install plugin from Decky
> 2. Click on Settings in left menu
> 3. Crash (screenshot)
> 
> **Screenshots**
> ![2023-07-04 00 00 34](https://github.com/Tormak9970/TabMaster/assets/52704675/8ae80b9f-8faa-455b-ad42-a3c14ebd1697)
> 
> **Enviroment Info:**
>  - SteamOS Version [last stable]
>  - SteamOS Update Channel [Stable]
>  - Decky Version [last stable]
>  - Decky Update Channel [Stable]
>  - TabMaster Version [last]
> 

Try deleting the json file in ~/homebrew/settings/TabMaster

**Comment by jessebofill** [comment]
@Tormak9970 this is same error emotion in discord had but I think they said after uninstalling playtimes it was good. @free-storage do you have playtimes installed?

**Comment by free-storage** [comment]
@jessebofill What is playtimes?

**Comment by free-storage** [comment]
> Try deleting the json file in ~/homebrew/settings/TabMaster

Did not help.

**Comment by Tormak9970** [comment]
> > Try deleting the json file in ~/homebrew/settings/TabMaster
> 
> Did not help.

damn. Did you happen to have a very old version of tab master installed at some point? would have been from a few months ago probably

**Comment by free-storage** [comment]
> We overlooked that the user may have a language other then english, gonna get that fixed soon

I assumed that this might be the problem. I'm waiting for a fix. Thank you.

**Comment by jessebofill** [comment]
> I assumed that this might be the problem. I'm waiting for a fix. Thank you.

the issue has been fixed and will be available in the next release.

**Comment by free-storage** [comment]
@jessebofill Great. When will the release be? The problem is critical, I think you need to make a release quickly.

**Comment by Tormak9970** [comment]
> @jessebofill Great. When will the release be? The problem is critical, I think you need to make a release quickly.

that's not up to us, its a matter of how long it takes to get reviewed once we submit the update, which i'll do later today

**Comment by free-storage** [comment]
> that's not up to us, its a matter of how long it takes to get reviewed once we submit the update, which i'll do later today

I didn't wait and manually changed this line:
`const homeElement = ret.props?.children?.props?.pages?.find((obj: any) => obj.route === '/settings/home')?.content;`

Fixed it. Thank you.
