### ISSUE TITLE
[FEAT]: Hidden Games Filter

### ISSUE THREAD

**Issue by drprofesq** [Tormak9970/TabMaster#53]
**Is your feature request related to a problem? Please describe.**
Normal collections in Steam ignore games that are marked as "Hidden". The Hidden option in Steam is useful for marking games that should not be shown in normal circumstances such on the Home screen. Even if they are installed, the only way to list or access those games is to go into settings and select the option to manage them, which opens a temporary list view. There is no way to add them to custom tabs or organize them in collections.

**Describe the solution you'd like**
Add a filter that can match games marked as Hidden. When selected, Hidden games should show in the tab instead of being ignored.

**Comment by Tormak9970** [comment]
> **Is your feature request related to a problem? Please describe.** Normal collections in Steam ignore games that are marked as "Hidden". The Hidden option in Steam is useful for marking games that should not be shown in normal circumstances such on the Home screen. Even if they are installed, the only way to list or access those games is to go into settings and select the option to manage them, which opens a temporary list view. There is no way to add them to custom tabs or organize them in collections.
> 
> **Describe the solution you'd like** Add a filter that can match games marked as Hidden. When selected, Hidden games should show in the tab instead of being ignored.

Its a good suggestion. Shouldn't be too hard to implement either.

**Comment by Tormak9970** [comment]
this as been added as of https://github.com/Tormak9970/TabMaster/commit/734177f299dfcabb530cd59b75c80b73884ecbff

**Comment by Tormak9970** [comment]
will be included in update v1.4.0
