### ISSUE TITLE
[BUG]: No reaction for non steam game removal

### ISSUE THREAD

**Issue by Tormak9970** [Tormak9970/TabMaster#62]
**Describe the bug**
We listen for when a game is installed/uninstalled, but we dont do the same for non steam games.

**Solution**
Have a reaction for the deckDesktop collection

**Comment by jessebofill** [comment]
Would that be like if a steam shortcut is added or removed?

**Comment by Tormak9970** [comment]
> Would that be like if a steam shortcut is added or removed?

Precisely

**Comment by jessebofill** [comment]
Gah I thought was covered with install reaction.

**Comment by Tormak9970** [comment]
implemented as of https://github.com/Tormak9970/TabMaster/commit/0f24fd0789201eae2b0a530bfb71229a90e64153
