### ISSUE TITLE
[FEAT]: make filters invertible

### ISSUE THREAD

**Issue by jessebofill** [Tormak9970/TabMaster#63]
Add option to invert any filter making it “not” that. in TabFilterSettings we’d just add an invert property. For simple filters like installed it’s options wouldn’t be necessary and could be removed.

**Comment by Tormak9970** [comment]
logic implemented as of https://github.com/Tormak9970/TabMaster/commit/245b327572664005af49f031606d419f1efe8537

**Comment by Tormak9970** [comment]
complete as of https://github.com/Tormak9970/TabMaster/commit/647e42521ec5f8b48a9aa22a5d0bb9a3dfabb0de
