### ISSUE TITLE
[FEAT]: Hidden Games tab

### ISSUE THREAD

**Issue by JohnnyKatswell** [Tormak9970/TabMaster#78]
**Is your feature request related to a problem? Please describe.**
Ability to create tab for hidden games, as an example - I use it to hide my completed games. It's pretty useful, especially when you have big library.

**Describe the solution you'd like**
I think it will be nice feature, since right now to view hidden games you need to go in the settings. As I understand - "Hidden Games" is a some special category, so there can be an easy implementation.

**Comment by Tormak9970** [comment]
> **Is your feature request related to a problem? Please describe.**
> Ability to create tab for hidden games, as an example - I use it to hide my completed games. It's pretty useful, especially when you have big library.
> 
> **Describe the solution you'd like**
> I think it will be nice feature, since right now to view hidden games you need to go in the settings. As I understand - "Hidden Games" is a some special category, so there can be an easy implementation.
> 

We've added this in v1.4.0 (see #53)
