### ISSUE TITLE
[FEAT]: Filter by Game type (???)

### ISSUE THREAD

**Issue by JohnGhostly** [Tormak9970/TabMaster#80]
I think it would be nice if you could filter games by whether they are a demo or a mod. It would be nice to be able to automatically filter demos into their own tab so your library doesn't get filled with them every nextfest. 
maybe we could also could add software and tools into that mix as well.

**Comment by Tormak9970** [comment]
> I think it would be nice if you could filter games by whether they are a demo or a mod. It would be nice to be able to automatically filter demos into their own tab so your library doesn't get filled with them every nextfest. 
> maybe we could also could add software and tools into that mix as well. 

Interesting idea. Can you verify this isnt possible with the tags? I thought there was a demo tag

**Comment by Tormak9970** [comment]
closing because this is achieveable with tags

**Comment by jessebofill** [comment]
To be clear 2.0.0 will include a demo filter as well as the ability include software and music in a tab. Tools are not able to be added to tabs due to how steam works. Mods will have to be identified using tags filter.
