### ISSUE TITLE
[BUG]: Tab does not refresh when non steam game is removed

### ISSUE THREAD

**Issue by Tormak9970** [Tormak9970/TabMaster#81]
**Describe the bug**
Switching tabs makes it update properly, should be a simple fix

**Comment by jessebofill** [comment]
I don’t think its a simple fix. We don’t have control of when a tab rerenders. It’s the same reason why any change to a tab requires switch tab/ remount for it to update

**Comment by Tormak9970** [comment]
the solution is worse then the issue, and its just an inconvenience
