### ISSUE TITLE
[BUG]: Navigating collection tabs jumps around

### ISSUE THREAD

**Issue by Tormak9970** [Tormak9970/TabMaster#88]
**Describe the bug**
When navigating the library, selection randomly jumps around

**Enviroment Info:**
 - SteamOS Update Channels: Preview and Bet
 - TabMaster Version 1.4.1

**Comment by jessebofill** [comment]
Does it jump back to the top?

**Comment by Tormak9970** [comment]
This appears to be because of Steam, not TabMaster. May consider trying to incorporate a fix if this is still present when beta goes to stable

**Comment by midnightcatwalk** [comment]
This also happens in the current stable OS for me (3.4.8). Every other time I press B to exit a game page and return to a collection from any tab but the first, the Library defaults to my first tab.

**Comment by Tormak9970** [comment]
> This also happens in the current stable OS for me (3.4.8), at least with collections including Steam Rom Manager-imported rom shortcuts. Every other time I press B to exit a game page and return to a collection from any tab but the first, the Library defaults to my first tab.
> 
> interestingly, this is _not_ the case for my Game Boy Color rom collection, which only has seven entries.

We've done some testing on this, and it seems to have been caused by a recent SteamOS update. It occurs on all channels, with and without TabMaster

**Comment by Tormak9970** [comment]
This seems to no longer be an issue. @jessebofill @midnightcatwalk can yall confirm? I believe valve fixed it

**Comment by jessebofill** [comment]
After applying the latest update it does appear to be fixed.

**Comment by Tormak9970** [comment]
Closing this as valve seems to have fixed this
