### ISSUE TITLE
[BUG]: No config verification

### ISSUE THREAD

**Issue by Tormak9970** [Tormak9970/TabMaster#9]
**Describe the bug**
Various issues can occur with the config

**Solution**
We need to validate the config in the backend. If its corrupted/incorrect, overwrite it, and notify the frontend to show a toast to the user

**This issue is for tracking the bug**

**Comment by jessebofill** [comment]
yeah we should verify for corruption. but we don't need to save friends/ tags etc in  / load from settings. we can just check them on load and store them in memory. reactions will handle changes

**Comment by Tormak9970** [comment]
> yeah we should verify for corruption. but we don't need to save friends/ tags etc in / load from settings. we can just check them on load and store them in memory. reactions will handle changes

i'm doing it so it works offline in some capacity

**Comment by jessebofill** [comment]
> > yeah we should verify for corruption. but we don't need to save friends/ tags etc in / load from settings. we can just check them on load and store them in memory. reactions will handle changes
> 
> i'm doing it so it works offline in some capacity

ah ok makes sense. but i just saw some errors related to those backend calls. didn't have a chance to look into them

**Comment by Tormak9970** [comment]
closing as validation has been added
