### ISSUE TITLE
[FEAT]: Different Tabs/Settings per Steam Account

### ISSUE THREAD

**Issue by Belickade** [Tormak9970/TabMaster#90]
Is it possible to add the ability to have separate tabs/settings per Steam Account?

I have an alt account that I only use to play 1 game (Fallout 76). To keep clutter to a minimum, I like to keep all other Tabs/Games marked as hidden. This works, however, when switching back to my main account, the settings I chose are shared with that of my main account.

**Comment by Tormak9970** [comment]
> Is it possible to add the ability to have separate tabs/settings per Steam Account?
> 
> I have an alt account that I only use to play 1 game (Fallout 76). To keep clutter to a minimum, I like to keep all other Tabs/Games marked as hidden. This works, however, when switching back to my main account, the settings I chose are shared with that of my main account.
> 

This should be very straightforward to implement, we'd just have to ask users if they want to use other user's settings if they have none

**Comment by Tormak9970** [comment]
complete as of https://github.com/Tormak9970/TabMaster/commit/f809aa980ca338f8c5dbe8b37845b5aa36348a1b. will be included in the next release

**Comment by Belickade** [comment]
Wow, so fast. I look forward to testing it out. Thanks.
