### ISSUE TITLE
[FLTR]: Filter Based on if a game is in a specific or any other tabs

### ISSUE THREAD

**Issue by Tormak9970** [Tormak9970/TabMaster#91]
**Describe the filter you'd like**
A filter that allows users to exclude/include games that are in another tab. This may be too big of a performance hit, and could lead to possible infinite loops, so may not be worth it.

**Comment by jessebofill** [comment]
Hmm. What would be the use case for this? Not really sure I see the point.

**Comment by Tormak9970** [comment]
> Hmm. What would be the use case for this? Not really sure I see the point. 

Honestly not sure. I've had multiple people rewuest it though, so thought itd be worth at least looking into

**Comment by jessebofill** [comment]
My first thought is also the problems you already mention and specifically with looping I don’t see any way to avoid that possibility.

**Comment by Tormak9970** [comment]
closing as not planned
